output "api_container_url" {
  description = "Serverless Container invocation URL. It remains private unless explicitly enabled."
  value       = yandex_serverless_container.api.url
}

output "api_repository_name" {
  description = "Container Registry repository used for Podman image pushes."
  value       = yandex_container_repository.api.name
}

output "api_service_account_id" {
  description = "Runtime service account attached to API revisions."
  value       = yandex_iam_service_account.api.id
}

output "migration_service_account_id" {
  description = "Runtime service account attached to migration revisions."
  value       = yandex_iam_service_account.migration.id
}

output "push_dispatcher_container_url" {
  description = "Private timer-driven push dispatcher URL. It has no public invocation binding."
  value       = yandex_serverless_container.push_dispatcher.url
}

output "push_dispatcher_service_account_id" {
  description = "Least-privilege runtime identity attached to the private push dispatcher."
  value       = yandex_iam_service_account.push_dispatcher.id
}

output "push_scheduler_service_account_id" {
  description = "Timer identity allowed to invoke the private push dispatcher."
  value       = yandex_iam_service_account.push_scheduler.id
}

output "database_cluster_id" {
  description = "Managed PostgreSQL cluster ID."
  value       = yandex_mdb_postgresql_cluster_v2.fit.id
}

output "database_name" {
  description = "Application database name."
  value       = yandex_mdb_postgresql_database.fit.name
}

output "database_owner_user" {
  description = "Migration owner username. Credentials are generated by Connection Manager."
  value       = yandex_mdb_postgresql_user.owner.name
}

output "database_runtime_user" {
  description = "Non-owner API username. Credentials are generated by Connection Manager."
  value       = yandex_mdb_postgresql_user.api.name
}

output "database_host_fqdn" {
  description = "Private PostgreSQL host FQDN for the later database baseline step."
  value       = yandex_mdb_postgresql_cluster_v2.fit.hosts["primary"].fqdn
}

output "database_url_secret_id" {
  description = "Lockbox secret metadata ID. No credential payload is stored by this configuration."
  value       = yandex_lockbox_secret.database_url.id
}

output "database_owner_url_secret_id" {
  description = "Legacy migration owner secret metadata ID retained during the credential transition."
  value       = yandex_lockbox_secret.database_owner_url.id
}

output "api_connection_secret_id" {
  description = "Connection Manager Lockbox secret used by the API runtime."
  value       = data.yandex_connectionmanager_connection.api.lockbox_secret.id
}

output "migration_connection_secret_id" {
  description = "Connection Manager Lockbox secret used by the migration runner."
  value       = data.yandex_connectionmanager_connection.owner.lockbox_secret.id
}

output "migration_container_url" {
  description = "Private migration runner URL, present only while an owner secret version is configured."
  value       = try(yandex_serverless_container.migration[0].url, null)
}
