import { expect, test } from '@playwright/test'

test('linked client sees only the published client progress view', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('client@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()

  await expect(page).toHaveURL(/\/me$/)
  await page.goto('/me/progress')
  await expect(page).toHaveURL(/\/me\/progress$/)
  await expect(page.getByRole('heading', { name: 'Мой прогресс' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Тренировки' })).toHaveCount(0)
  await expect(page.getByRole('tab', { name: 'Неделя' })).toHaveCount(0)
  await expect(page.getByText('Твой прогресс', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '1 месяц' })).toHaveClass(/active/)
  await expect(page.getByText(/рабочий вес в жиме вырос на 4%/i)).toBeVisible()
  await expect(page.getByText('Динамика упражнений')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Твоя цель' })).toBeVisible()
  await expect(page.getByText('Повысить силовые показатели и улучшить выносливость')).toBeVisible()
  await expect(page.getByText(/Рост рабочего веса поддерживает цель/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Что делать дальше' })).toBeVisible()
  await expect(page.getByText(/причина максимального перерыва/)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Обновить' })).toBeVisible()
  await page.getByText('ЗАМЕРЫ ТЕЛА', { exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByText('ЗАМЕРЫ ТЕЛА', { exact: true })).toBeVisible()

  await page.goto('/clients')
  await expect(page).toHaveURL(/\/me$/)
})

test('trainer reviews the client copy separately from internal attention items', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('trainer@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/today$/)
  await page.goto('/progress/11111111-1111-4111-8111-111111111111')

  const overview = page.locator('.trainer-progress-overview-card')
  await expect(page.getByRole('heading', { name: 'Главное по клиенту' })).toBeVisible()
  await expect(overview.getByText(/трениров(?:ка|ки|ок) за неделю$/)).toBeVisible()
  await expect(overview.getByText(/Положительная динамика есть, но период пока короткий/)).toBeVisible()
  await expect(overview.getByText(/Уточнить: достаточно ли четырёх наблюдений/)).toBeVisible()
  await expect(page.locator('.trainer-progress-details')).not.toHaveAttribute('open', '')
  await expect(page.locator('.trainer-measurements')).not.toHaveAttribute('open', '')
  await expect(page.getByText('ЗАМЕРЫ И ПОКАЗАТЕЛИ', { exact: true })).toBeVisible()

  await page.locator('.trainer-progress-details > summary').click()
  await expect(page.getByLabel('Регулярность тренировок')).toBeVisible()
  const trainerAnalysis = page.getByLabel('ИИ-анализ тренировок')
  await expect(trainerAnalysis.getByText('Анализ прогресса')).toBeVisible()
  await expect(trainerAnalysis.getByText('Доступно клиенту')).toBeVisible()
  await expect(trainerAnalysis.getByText('На что обратить внимание')).toBeVisible()
  await expect(trainerAnalysis.getByText('Динамика упражнений')).toBeVisible()
  await page.getByRole('button', { name: 'Проверить версию для клиента' }).click()
  await expect(page.getByLabel('Главный результат')).toHaveValue(/рабочий вес в жиме вырос на 4%/)
  await expect(page.getByRole('button', { name: 'Сохранить клиентскую версию' })).toBeVisible()
})
