import { expect, test } from '@playwright/test'

test('global rollout gives a new client the monochrome Progress identity', async ({ page }, testInfo) => {
  await page.goto('/auth')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByLabel('Тип аккаунта').selectOption('client')
  await page.getByLabel('Имя').fill('Progress без preview')
  await page.getByLabel('Email').fill(`progress-no-preview-${testInfo.workerIndex}-${Date.now()}@fit.local`)
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await expect(page).toHaveURL(/\/me$/)

  await page.goto('/me/progress')
  await expect(page.getByRole('heading', { name: 'Мой прогресс' })).toBeVisible()
  await expect(page.locator('.phone-frame')).toHaveClass(/progress-identity/)
  await expect(page.locator('html')).toHaveClass(/identity-monochrome-preview/)
})

test('linked client sees only the published client progress view', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('client@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()

  await expect(page).toHaveURL(/\/me$/)
  await page.goto('/me/profile')
  await expect(page.getByRole('radiogroup', { name: 'Вид фигуры' })).toBeVisible()
  await expect(page.getByRole('radio', { name: 'Реальная фигура' })).toBeChecked()
  await page.getByRole('radio', { name: 'Схема' }).click()
  await page.goto('/me/progress')
  await expect(page).toHaveURL(/\/me\/progress$/)
  await expect(page.getByRole('heading', { name: 'Мой прогресс' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Тренировки' })).toHaveCount(0)
  await expect(page.getByRole('tab', { name: 'Неделя' })).toHaveCount(0)
  await expect(page.getByText('Твой прогресс', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '1 месяц' })).toHaveClass(/active/)
  await page.getByRole('button', { name: 'Прогресс', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Где выросли результаты' })).toBeVisible()
  await expect(page.getByRole('group', { name: 'Анатомическая схема мышц, вид спереди' })).toBeVisible()
  await page.goto('/me/profile')
  await page.getByRole('radio', { name: 'Реальная фигура' }).click()
  await page.goto('/me/progress')
  await expect(page.getByRole('group', { name: 'Атлетичная женщина, вид спереди' })).toBeVisible()
  await page.getByRole('button', { name: 'Подробный анализ' }).click()
  await expect(page.getByRole('dialog', { name: 'Подробный анализ' })).toBeVisible()
  await expect(page.getByText(/Жим лёжа: рабочий вес вырос с 72 до 75 кг/i)).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть' }).click()
  await expect(page.getByText('Для твоей цели', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Повысить силовые показатели и улучшить выносливость' })).toBeVisible()
  await expect(page.getByText('Не настроено', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Настроить оценку' })).toHaveAttribute('href', '/me/goal')
  await expect(page.getByText(/Рост рабочего веса поддерживает цель/)).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'На следующей тренировке' })).toHaveCount(0)
  await expect(page.getByText(/причина максимального перерыва/)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Обновить' })).toBeVisible()
  await page.getByText('ЗАМЕРЫ И ПОКАЗАТЕЛИ', { exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByText('ЗАМЕРЫ И ПОКАЗАТЕЛИ', { exact: true })).toBeVisible()

  await page.goto('/me/goal')
  await expect(page.locator('.phone-frame')).toHaveClass(/client-goal-identity/)
  await expect(page.getByRole('heading', { name: 'Моя цель' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Как оценивать цель' })).toBeVisible()
  await expect(page.getByLabel('Цель')).toHaveValue('Повысить силовые показатели и улучшить выносливость')
  await expect(page.getByText(/Цель сохранится как текст без автоматической оценки/)).toBeVisible()

  await page.goto('/clients')
  await expect(page).toHaveURL(/\/me$/)
})

test('trainer reviews the client copy separately from internal attention items', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('trainer@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/today$/)
  await page.goto('/profile')
  await expect(page.getByRole('radiogroup', { name: 'Вид фигуры' })).toBeVisible()
  await expect(page.getByRole('radio', { name: 'Реальная фигура' })).toBeChecked()
  await page.getByRole('radio', { name: 'Схема' }).click()
  await page.goto('/clients/11111111-1111-4111-8111-111111111111')
  await expect(page.getByRole('radiogroup', { name: 'Вид фигуры' })).toHaveCount(0)
  await page.goto('/progress/11111111-1111-4111-8111-111111111111')

  await expect(page.getByRole('heading', { name: 'Прогресс', exact: true })).toBeVisible()
  await expect(page.getByLabel('Тренировки за неделю')).toBeVisible()
  await expect(page.getByLabel('Тренировки за неделю').locator('strong')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Открыть замеры и показатели' })).toBeVisible()
  await expect(page.locator('details')).toHaveCount(0)

  const trainerAnalysis = page.getByLabel('ИИ-анализ тренировок')
  await expect(trainerAnalysis.getByRole('radiogroup', { name: 'Вид фигуры' })).toHaveCount(0)
  await expect(trainerAnalysis.getByRole('group', { name: 'Атлетичный мужчина, вид спереди' })).toHaveCount(0)
  await expect(trainerAnalysis.getByRole('group', { name: 'Атлетичная женщина, вид спереди' })).toHaveCount(0)
  await expect(trainerAnalysis.getByRole('group', { name: 'Анатомическая схема мышц, вид спереди' })).toBeVisible()
  await expect(trainerAnalysis.getByText('Анализ прогресса')).toBeVisible()
  await expect(trainerAnalysis.getByText('Доступно клиенту')).toBeVisible()
  await expect(trainerAnalysis.getByText('На что обратить внимание')).toBeVisible()
  await expect(trainerAnalysis.getByText('Динамика упражнений')).toHaveCount(0)
  await trainerAnalysis.getByRole('button', { name: 'Подробный анализ' }).click()
  const detailedAnalysis = page.getByRole('dialog', { name: 'Подробный анализ' })
  await expect(detailedAnalysis.getByText('Динамика упражнений')).toBeVisible()
  await expect(detailedAnalysis.getByText('Ритм тренировок')).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть' }).click()
  await page.getByRole('button', { name: 'Версия для спортсмена' }).click()
  const clientCopy = page.getByRole('dialog', { name: 'Версия для спортсмена' })
  await expect(clientCopy).toBeVisible()
  await expect(clientCopy.getByRole('textbox', { name: 'Главный результат', exact: true }))
    .toHaveValue(/рабочий вес в жиме вырос на 4%/)
  await expect(clientCopy.getByRole('button', { name: 'Сохранить клиентскую версию' })).toBeVisible()
})
