import { expect, test } from '@playwright/test'

test('linked client sees only the published client progress view', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('client@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()

  await expect(page).toHaveURL(/\/me$/)
  await page.goto('/me/profile')
  await expect(page.getByRole('radiogroup', { name: 'Вид фигуры' })).toBeVisible()
  await expect(page.getByRole('radio', { name: 'Женская фигура' })).toBeChecked()
  await expect(page.getByRole('radio', { name: 'Мужская фигура' })).toHaveCount(0)
  await page.getByRole('radio', { name: 'Схема' }).click()
  await page.goto('/me/progress')
  await expect(page).toHaveURL(/\/me\/progress$/)
  await expect(page.getByRole('heading', { name: 'Мой прогресс' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Тренировки' })).toHaveCount(0)
  await expect(page.getByRole('tab', { name: 'Неделя' })).toHaveCount(0)
  await expect(page.getByText('Твой прогресс', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '1 месяц' })).toHaveClass(/active/)
  await page.getByRole('button', { name: 'Прогресс', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Где выросли результаты' })).toBeVisible()
  await expect(page.getByRole('group', { name: 'Нейтральная фигура спортсмена, вид спереди' })).toBeVisible()
  await page.goto('/me/profile')
  await page.getByRole('radio', { name: 'Женская фигура' }).click()
  await page.goto('/me/progress')
  await expect(page.getByRole('group', { name: 'Атлетичная женщина, вид спереди' })).toBeVisible()
  await page.getByRole('button', { name: 'Подробный анализ' }).click()
  await expect(page.getByRole('dialog', { name: 'Подробный анализ' })).toBeVisible()
  await expect(page.getByText(/Жим лёжа: рабочий вес вырос с 72 до 75 кг/i)).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть' }).click()
  await expect(page.getByRole('heading', { name: 'Для твоей цели' })).toBeVisible()
  await expect(page.getByText('Повысить силовые показатели и улучшить выносливость')).toBeVisible()
  await expect(page.getByText(/Рост рабочего веса поддерживает цель/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'На следующей тренировке' })).toBeVisible()
  await expect(page.getByText(/причина максимального перерыва/)).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Обновить' })).toBeVisible()
  await page.getByText('ЗАМЕРЫ И ПОКАЗАТЕЛИ', { exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByText('ЗАМЕРЫ И ПОКАЗАТЕЛИ', { exact: true })).toBeVisible()

  await page.goto('/clients')
  await expect(page).toHaveURL(/\/me$/)
})

test('trainer reviews the client copy separately from internal attention items', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('trainer@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/today$/)
  await page.goto('/profile')
  await expect(page.getByRole('radio', { name: 'Мужская фигура' })).toBeVisible()
  await page.getByRole('radio', { name: 'Мужская фигура' }).click()
  await page.goto('/progress/11111111-1111-4111-8111-111111111111')

  await expect(page.getByRole('heading', { name: 'Прогресс' })).toBeVisible()
  await expect(page.getByLabel('Тренировки за неделю')).toBeVisible()
  await expect(page.getByLabel('Тренировки за неделю').locator('strong')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Открыть замеры и показатели' })).toBeVisible()
  await expect(page.locator('details')).toHaveCount(0)

  const trainerAnalysis = page.getByLabel('ИИ-анализ тренировок')
  await expect(trainerAnalysis.getByRole('group', { name: 'Атлетичный мужчина, вид спереди' })).toBeVisible()
  await expect(trainerAnalysis.getByRole('group', { name: 'Атлетичная женщина, вид спереди' })).toHaveCount(0)
  await expect(trainerAnalysis.getByText('Анализ прогресса')).toBeVisible()
  await expect(trainerAnalysis.getByText('Доступно клиенту')).toBeVisible()
  await expect(trainerAnalysis.getByText('На что обратить внимание')).toBeVisible()
  await expect(trainerAnalysis.getByText('Динамика упражнений')).toBeVisible()
  await page.getByRole('button', { name: 'Версия для спортсмена' }).click()
  await expect(page.getByRole('dialog', { name: 'Версия для спортсмена' })).toBeVisible()
  await expect(page.getByLabel('Главный результат')).toHaveValue(/рабочий вес в жиме вырос на 4%/)
  await expect(page.getByRole('button', { name: 'Сохранить клиентскую версию' })).toBeVisible()
})
