import { expect, test } from '@playwright/test'

test('invited trainer stays disconnected after profile reload and client card disappears', async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  const suffix = `${testInfo.workerIndex}-${Date.now()}`
  const clientEmail = `disconnect-client-${suffix}@fit.local`
  const trainerEmail = `disconnect-trainer-${suffix}@fit.local`
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/auth')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByLabel('Тип аккаунта').selectOption('client')
  await page.getByLabel('Имя').fill('Клиент отвязки')
  await page.getByLabel('Email').fill(clientEmail)
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await expect(page).toHaveURL(/\/me$/)
  await page.goto('/me/edit')
  await page.getByLabel('Пол').selectOption('female')
  await page.getByLabel('Возраст').fill('30')
  await page.getByLabel('Рост, см').fill('170')
  await page.getByRole('button', { name: 'Сохранить профиль' }).click()
  await expect(page).toHaveURL(/\/me$/)
  await page.goto('/me/profile')
  await page.getByRole('button', { name: 'Пригласить тренера' }).click()
  const code = (await page.getByText(/Код для тренера:/).textContent())?.match(/[A-F0-9]{12}/)?.[0]
  expect(code).toBeTruthy()
  await page.getByRole('button', { name: 'Выйти' }).click()

  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByLabel('Имя').fill('Приглашённый тренер отвязки')
  await page.getByLabel('Email').fill(trainerEmail)
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await expect(page).toHaveURL(/\/today$/)
  await page.goto('/join')
  await page.getByLabel('Код приглашения').fill(code!)
  await page.getByRole('button', { name: 'Присоединиться' }).click()
  await page.getByRole('button', { name: 'Открыть карточку' }).click()
  await expect(page).toHaveURL(/\/clients\/[0-9a-f-]+$/)
  await page.goto('/profile')
  await page.getByRole('button', { name: 'Выйти' }).click()

  await page.getByLabel('Email').fill(clientEmail)
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/me$/)
  await page.goto('/me/profile')
  await expect(page.getByText('Приглашённый тренер отвязки', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Отключить' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: 'Отключить' }).click()
  await expect(page.getByText('Сейчас вы занимаетесь самостоятельно.')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Сейчас вы занимаетесь самостоятельно.')).toBeVisible()
  await expect(page.getByText('Приглашённый тренер отвязки', { exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 430, height: 932 })
  await page.getByRole('switch', { name: 'Тёмная тема' }).check()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Выйти' }).click()
  await page.getByLabel('Email').fill(clientEmail)
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/me$/)
  await page.goto('/me/profile')
  await expect(page.getByText('Сейчас вы занимаетесь самостоятельно.')).toBeVisible()
  await page.getByRole('button', { name: 'Выйти' }).click()

  await page.getByLabel('Email').fill(trainerEmail)
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/today$/)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/clients')
  await expect(page.getByRole('heading', { name: 'Клиенты' })).toBeVisible()
  await expect(page.getByText('Клиент отвязки', { exact: true })).toHaveCount(0)
})

test('client profile: trainer can complete a client profile from the detail page', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('trainer@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/(today|clients)$/)
  await page.goto('/clients/11111111-1111-4111-8111-111111111111')

  await page.getByRole('button', { name: 'Действия с профилем спортсмена' }).click()
  await page.getByRole('menuitem', { name: 'Редактировать профиль' }).click()
  await expect(page.getByRole('heading', { name: 'Редактировать клиента' })).toBeVisible()
  await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Анна Смирнова')
  await expect(page.getByLabel('Возраст')).toBeVisible()
  await expect(page.getByLabel('Цель')).toBeVisible()
})

test('global rollout gives a new client the Profile and Card Edit identity', async ({ page }, testInfo) => {
  await page.goto('/auth')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await page.getByLabel('Тип аккаунта').selectOption('client')
  await page.getByLabel('Имя').fill('Профиль без preview')
  await page.getByLabel('Email').fill(`profile-no-preview-${testInfo.workerIndex}-${Date.now()}@fit.local`)
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Создать аккаунт' }).click()
  await expect(page).toHaveURL(/\/me$/)

  await page.goto('/me/profile')
  await expect(page.getByRole('heading', { name: 'Профиль' })).toBeVisible()
  await expect(page.locator('.phone-frame')).toHaveClass(/client-profile-shell-identity/)
  await expect(page.locator('html')).toHaveClass(/ui-identity/)

  await page.goto('/me/edit')
  await expect(page.locator('.phone-frame')).toHaveClass(/client-card-edit-identity/)
  await expect(page.locator('html')).toHaveClass(/ui-identity/)
})
