import { expect, test } from '@playwright/test'

test('trainer can create client, complete workout and save progress', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('trainer@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page.getByRole('heading', { name: 'Клиенты' })).toBeVisible()

  await page.getByRole('link', { name: 'Добавить' }).click()
  await page.getByLabel('Имя').fill('Анна Тестова')
  await page.getByLabel('Начальный вес, кг').fill('61.5')
  await page.getByLabel('Цель').fill('Стать сильнее')
  await page.getByRole('button', { name: 'Сохранить' }).click()
  await expect(page.getByRole('heading', { name: 'Анна Тестова' })).toBeVisible()
  const clientUrl = page.url()

  await page.getByRole('link', { name: /Запланировать тренировку/ }).click()
  await page.getByLabel('Клиент').selectOption({ label: 'Анна Тестова' })
  await page.getByLabel('Добавить упражнение').selectOption('barbell-squat')
  await page.getByLabel('Вес').fill('40')
  await page.getByLabel('Повторы').fill('10')
  await page.getByRole('button', { name: 'Сохранить' }).click()
  await expect(page.getByRole('heading', { name: 'Тренировка', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Начать' }).click()
  await expect(page.getByText('● LIVE', { exact: true })).toBeVisible()
  await page.locator('input[name="weightKg"]').fill('42.5')
  await page.locator('input[name="reps"]').fill('9')
  await page.getByRole('heading', { name: 'Live-тренировка' }).click()
  await page.waitForTimeout(300)
  await page.getByRole('button', { name: 'Подтвердить подход' }).click()
  await expect(page.getByRole('button', { name: 'Подтверждено' })).toBeVisible()
  await page.getByRole('button', { name: 'Завершить тренировку' }).click()
  await expect(page.getByText('Готово')).toBeVisible()

  await page.goto(clientUrl)
  await page.getByRole('link', { name: 'Замеры и аналитика' }).click()
  await page.getByLabel('Дата').fill('2026-07-20')
  await page.getByLabel('Вес, кг').fill('61')
  await page.getByRole('button', { name: 'Сохранить замер' }).click()
  await expect(page.getByText('61 кг')).toBeVisible()
})
