import { expect, test } from '@playwright/test'

test('trainer publishes a profile and athlete finds it in the catalog', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('trainer@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/(today|clients)$/)

  await page.goto('/profile/trainer')
  await expect(page).toHaveURL(/profile$/)
  await expect(page.getByRole('link', { name: 'Анкета тренера' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Настройки профиля' })).toBeVisible()
  const coachmarkDismiss = page.getByRole('button', { name: 'Понятно' })
  if (await coachmarkDismiss.isVisible()) await coachmarkDismiss.click()
  const profile = page.getByRole('region', { name: 'Анкета тренера' })
  await profile.getByRole('button', { name: /Редактировать|Заполнить анкету/ }).click()
  const editor = profile.getByRole('form', { name: 'Редактирование анкеты тренера' })
  await expect(editor).toHaveClass(/trainer-profile-edit-card/)
  await expect(editor.locator('.trainer-profile-fields')).toHaveCount(0)
  await editor.getByLabel('Имя в анкете').fill('Анна Иванова')
  await editor.getByLabel('О себе').fill('Помогаю безопасно начать силовые тренировки, встроить движение в обычную жизнь и видеть понятный прогресс без перегрузки.')
  await editor.getByLabel('Направления').fill('Силовые, снижение веса')
  await editor.getByRole('switch', { name: 'Онлайн' }).check()
  await editor.getByLabel('Город').fill('Москва')
  await editor.getByLabel('Как проходят занятия').fill('Созваниваемся раз в неделю и корректируем план.')
  await editor.locator('input[type="file"]').setInputFiles({
    name: 'avatar.png',
    mimeType: 'image/png',
    buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64'),
  })
  await editor.locator('.trainer-profile-form-disclosure > summary').click()
  await editor.getByLabel('Образование и квалификация').fill('Высшее физкультурное образование.')
  await editor.getByRole('button', { name: 'Добавить сертификат' }).click()
  await editor.getByLabel('Название сертификата 1').fill('Персональный тренер')
  await editor.getByLabel('Организация 1').fill('Fit Academy')
  await editor.getByLabel('Год сертификата 1').fill('2025')
  await editor.getByRole('button', { name: 'Сохранить' }).click()
  await expect(profile.getByRole('heading', { name: 'Анна Иванова' })).toBeVisible()
  await expect(profile.getByRole('button', { name: 'Редактировать' })).toBeVisible()
  await expect(profile.locator('img.trainer-card-avatar')).toBeVisible()
  await profile.getByText('Образование и сертификаты · 1').click()
  await expect(profile.getByText('Высшее физкультурное образование.')).toBeVisible()
  await expect(profile.getByText('Персональный тренер')).toBeVisible()
  const publication = profile.locator('.trainer-publication-disclosure')
  await publication.locator('summary').click()
  const publishButton = publication.getByRole('button', { name: /Опубликовать|Обновить публикацию/ })
  if (await publishButton.isVisible()) await publishButton.click()
  await expect(publication.getByText(/Доступна по ссылке|Видна в каталоге/)).toBeVisible()
  const publicLink = await publication.getByRole('link', { name: 'Открыть анкету' }).getAttribute('href')
  expect(publicLink).toMatch(/^\/trainers\/[0-9a-f-]+$/)
  const publicRequest = page.waitForResponse((response) => response.url().includes('/rpc/get_public_trainer_profile'))
  await page.goto(publicLink!)
  const publicResponse = await publicRequest
  expect(publicResponse.status()).toBe(200)
  await expect(page.getByRole('heading', { name: 'Анна Иванова' })).toBeVisible()
  await expect(page.getByText('Спортсмены видят последнюю опубликованную версию.')).toHaveCount(0)
  await expect(page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).resolves.toBe(true)

  await page.goto('/profile')
  const profileAfterPublish = page.getByRole('region', { name: 'Анкета тренера' })
  await profileAfterPublish.locator('.trainer-publication-disclosure summary').click()
  const catalogSwitch = profileAfterPublish.getByRole('switch', { name: 'Показывать в каталоге' })
  if (await catalogSwitch.isChecked()) {
    const hideFromCatalogRequest = page.waitForResponse((response) => response.url().includes('/rpc/set_trainer_profile_catalog_listing'))
    await catalogSwitch.click()
    expect((await hideFromCatalogRequest).status()).toBe(200)
    await expect(catalogSwitch).not.toBeChecked()
  }
  const catalogRequest = page.waitForResponse((response) => response.url().includes('/rpc/set_trainer_profile_catalog_listing'))
  await catalogSwitch.click()
  expect((await catalogRequest).status()).toBe(200)
  await expect(catalogSwitch).toBeChecked()

  await page.getByRole('link', { name: 'Настройки профиля' }).click()
  await expect(page).toHaveURL(/\/profile\/settings$/)
  await page.getByRole('button', { name: 'Выйти' }).click()
  await expect(page).toHaveURL(/\/auth$/)
  await page.getByLabel('Email').fill('client@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/me$/)

  await page.goto('/me/profile')
  await page.getByRole('link', { name: /Найти тренера/ }).click()
  await expect(page).toHaveURL(/\/me\/trainers$/)
  await expect(page.getByRole('heading', { level: 1, name: 'Тренеры' })).toBeVisible()
  const results = page.getByRole('region', { name: 'Найденные тренеры' })
  await expect(results.getByRole('heading', { name: 'Анна Иванова' })).toBeVisible()

  await page.getByRole('button', { name: 'Фильтры' }).click()
  await page.getByLabel('Направление').fill('снижение веса')
  await page.getByRole('button', { name: 'Найти' }).click()
  await expect(results.getByRole('heading', { name: 'Анна Иванова' })).toBeVisible()
  await results.getByRole('link', { name: 'Посмотреть анкету' }).click()
  await expect(page).toHaveURL(/\/trainers\/[0-9a-f-]+$/)
  await expect(page.getByRole('heading', { name: 'Анна Иванова' })).toBeVisible()
  await page.getByRole('button', { name: 'Назад' }).click()
  await expect(page).toHaveURL(/\/me\/trainers$/)
  await expect(page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).resolves.toBe(true)
})
