import { expect, test } from '@playwright/test'

test('trainer saves, previews and publishes a professional profile', async ({ page }) => {
  await page.goto('/auth')
  await page.getByLabel('Email').fill('trainer@fit.local')
  await page.getByLabel('Пароль').fill('FitLocal123!')
  await page.getByRole('button', { name: 'Войти' }).click()
  await expect(page).toHaveURL(/\/(today|clients)$/)

  await page.goto('/profile/trainer')
  await expect(page).toHaveURL(/profile$/)
  await expect(page.getByRole('link', { name: 'Анкета тренера' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Профессиональная анкета' })).toBeVisible()
  const profile = page.getByRole('region', { name: 'Профессиональная анкета' })
  await profile.getByLabel('Как вас увидят спортсмены').fill('Анна Иванова')
  await profile.getByLabel('О себе').fill('Помогаю безопасно начать силовые тренировки и видеть понятный прогресс.')
  await profile.getByLabel('Направления').fill('Силовые, снижение веса')
  await profile.getByRole('switch', { name: 'Онлайн' }).check()
  await profile.getByLabel('Город').fill('Москва')
  await profile.getByLabel('Как проходят занятия').fill('Созваниваемся раз в неделю и корректируем план.')
  await profile.getByRole('button', { name: 'Предпросмотр' }).click()
  await expect(page.getByText('ПРЕДПРОСМОТР', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Анна Иванова' })).toBeVisible()

  const actionPanel = page.locator('.trainer-profile-actions-panel')
  await expect(actionPanel).toBeVisible()
  await expect(actionPanel.evaluate((element) => getComputedStyle(element).position)).resolves.not.toBe('sticky')
  await profile.getByRole('button', { name: 'Опубликовать' }).click()
  await expect(page.getByText('Анкета опубликована')).toBeVisible()
  const publicLink = await page.getByRole('link', { name: 'Открыть' }).getAttribute('href')
  expect(publicLink).toMatch(/^\/trainers\/[0-9a-f-]+$/)
  const publicRequest = page.waitForResponse((response) => response.url().includes('/rpc/get_public_trainer_profile'))
  await page.goto(publicLink!)
  const publicResponse = await publicRequest
  expect(publicResponse.status()).toBe(200)
  await expect(page.getByRole('heading', { name: 'Анна Иванова' })).toBeVisible()
  await expect(page.getByText('Спортсмены видят последнюю опубликованную версию.')).toHaveCount(0)
  await expect(page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).resolves.toBe(true)
})
