// Approved editorial list: FIT_final_core_uncommon_rare_remove.xlsx, 2026-09-03.
// Keep refs stable: this map controls presentation, never historical data deletion.
export interface CatalogDecision { name: string; tier: "core" | "uncommon" | "rare" | "retired"; action?: "duplicate" | "variant" | "format"; target?: string }
export const EXERCISE_CATALOG_DECISIONS: Readonly<Record<string, CatalogDecision>> = {
  "dumbbell-bench-press": {"name":"Жим гантелей лёжа","tier":"core"},
  "fedb-incline-dumbbell-press": {"name":"Жим гантелей на наклонной скамье","tier":"core"},
  "fedb-machine-bench-press": {"name":"Жим от груди в тренажёре","tier":"core"},
  "bench-press": {"name":"Жим штанги лёжа","tier":"core"},
  "incline-bench-press": {"name":"Жим штанги на наклонной скамье","tier":"core"},
  "push-ups": {"name":"Отжимания","tier":"core"},
  "dips": {"name":"Отжимания на брусьях","tier":"core"},
  "dumbbell-fly": {"name":"Разведение гантелей лёжа","tier":"core"},
  "fedb-cable-crossover": {"name":"Сведение рук в кроссовере","tier":"core"},
  "pec-deck": {"name":"Сведение рук в тренажёре","tier":"core"},
  "vital-air-bike-sprint": {"name":"Аэробайк","tier":"core"},
  "running": {"name":"Бег","tier":"core"},
  "vital-treadmill-running": {"name":"Бег на дорожке","tier":"core"},
  "burpees": {"name":"Берпи","tier":"core"},
  "stationary-bike": {"name":"Велотренажёр","tier":"core"},
  "rowing-machine": {"name":"Гребной тренажёр","tier":"core"},
  "vital-stair-climber": {"name":"Лестничный тренажёр","tier":"core"},
  "jump-rope": {"name":"Прыжки со скакалкой","tier":"core"},
  "vital-stepper-machine": {"name":"Степпер","tier":"core"},
  "walking": {"name":"Ходьба","tier":"core"},
  "vital-treadmill-walking": {"name":"Ходьба на дорожке","tier":"core"},
  "elliptical": {"name":"Эллиптический тренажёр","tier":"core"},
  "side-plank": {"name":"Боковая планка","tier":"core"},
  "fedb-air-bike": {"name":"Велосипед для пресса","tier":"core"},
  "fedb-standing-cable-wood-chop": {"name":"Дровосек в блоке стоя","tier":"core"},
  "fedb-pallof-press": {"name":"Жим Паллоффа в блоке","tier":"core"},
  "cat-cow": {"name":"Кошка-корова","tier":"core"},
  "fedb-dead-bug": {"name":"Мёртвый жук","tier":"core"},
  "thoracic-mobility": {"name":"Мобилизация грудного отдела","tier":"core"},
  "fedb-reverse-crunch": {"name":"Обратные скручивания","tier":"core"},
  "plank": {"name":"Планка","tier":"core"},
  "leg-raise": {"name":"Подъём ног лёжа","tier":"core"},
  "crunches": {"name":"Скручивания","tier":"core"},
  "fedb-monster-walk": {"name":"Боковая ходьба с резиной","tier":"core"},
  "vital-dumbbell-bulgarian-split-squat": {"name":"Болгарский сплит-присед с гантелями","tier":"core"},
  "lunges": {"name":"Выпады со штангой","tier":"core"},
  "fedb-hack-squat": {"name":"Гакк-присед в тренажёре","tier":"core"},
  "vital-dumbbell-goblet-squat": {"name":"Гоблет-присед с гантелью","tier":"core"},
  "dynamic-hamstring-stretch": {"name":"Динамическая растяжка задней поверхности бедра","tier":"core"},
  "leg-press": {"name":"Жим ногами в тренажёре","tier":"core"},
  "fedb-dumbbell-step-ups": {"name":"Зашагивания с гантелями","tier":"core"},
  "ankle-mobility": {"name":"Мобилизация голеностопа","tier":"core"},
  "hip-mobility": {"name":"Мобилизация тазобедренных суставов","tier":"core"},
  "fedb-thigh-abductor": {"name":"Отведение бёдер в тренажёре","tier":"core"},
  "fedb-seated-calf-raise": {"name":"Подъём на носки сидя в тренажёре","tier":"core"},
  "calf-raise": {"name":"Подъём на носки стоя в тренажёре","tier":"core"},
  "fedb-thigh-adductor": {"name":"Приведение бёдер в тренажёре","tier":"core"},
  "barbell-squat": {"name":"Присед со штангой","tier":"core"},
  "fedb-bodyweight-squat": {"name":"Приседания без веса","tier":"core"},
  "leg-extension": {"name":"Разгибание ног в тренажёре","tier":"core"},
  "romanian-deadlift": {"name":"Румынская тяга со штангой","tier":"core"},
  "leg-curl": {"name":"Сгибание ног лёжа в тренажёре","tier":"core"},
  "band-external-rotation": {"name":"Внешняя ротация плеча с резиной","tier":"core"},
  "vital-standing-dumbbell-press": {"name":"Жим гантелей над головой стоя","tier":"core"},
  "overhead-press": {"name":"Жим штанги над головой стоя","tier":"core"},
  "shoulder-mobility": {"name":"Мобилизация плеч","tier":"core"},
  "vital-reverse-pec-deck": {"name":"Обратная бабочка в тренажёре","tier":"core"},
  "lateral-raise": {"name":"Разведение гантелей в стороны","tier":"core"},
  "rear-delt-fly": {"name":"Разведение гантелей на заднюю дельту","tier":"core"},
  "fedb-face-pull": {"name":"Тяга каната к лицу","tier":"core"},
  "joint-warmup": {"name":"Суставная разминка","tier":"core"},
  "hammer-curl": {"name":"Молотковые сгибания с гантелями","tier":"core"},
  "barbell-curl": {"name":"Подъём штанги на бицепс","tier":"core"},
  "fedb-cable-rope-overhead-triceps-extension": {"name":"Разгибание рук из-за головы с канатом в блоке","tier":"core"},
  "triceps-pushdown": {"name":"Разгибание рук на трицепс в блоке","tier":"core"},
  "biceps-curl": {"name":"Сгибание рук с гантелями","tier":"core"},
  "hyperextension": {"name":"Гиперэкстензия","tier":"core"},
  "fedb-leverage-iso-row": {"name":"Горизонтальная тяга в рычажном тренажёре","tier":"core"},
  "fedb-suspended-row": {"name":"Горизонтальная тяга на петлях","tier":"core"},
  "pull-ups": {"name":"Подтягивания","tier":"core"},
  "fedb-band-assisted-pull-up": {"name":"Подтягивания с резиной","tier":"core"},
  "deadlift": {"name":"Становая тяга со штангой","tier":"core"},
  "lat-pulldown": {"name":"Тяга верхнего блока","tier":"core"},
  "dumbbell-row": {"name":"Тяга гантели в наклоне","tier":"core"},
  "seated-cable-row": {"name":"Тяга нижнего блока","tier":"core"},
  "barbell-row": {"name":"Тяга штанги в наклоне","tier":"core"},
  "vital-kettlebell-swing": {"name":"Мах гири двумя руками","tier":"core"},
  "fedb-one-legged-cable-kickback": {"name":"Отведение ноги назад в блоке","tier":"core"},
  "fedb-barbell-hip-thrust": {"name":"Хип-траст со штангой с опорой на скамью","tier":"core"},
  "fedb-butt-lift-bridge": {"name":"Ягодичный мост на полу","tier":"core"},
  "fedb-smith-machine-decline-press": {"name":"Жим в Смите на скамье с отрицательным наклоном","tier":"uncommon"},
  "fedb-decline-dumbbell-bench-press": {"name":"Жим гантелей на скамье с отрицательным наклоном","tier":"uncommon"},
  "fedb-one-arm-kettlebell-floor-press": {"name":"Жим гири с пола одной рукой","tier":"uncommon"},
  "fedb-smith-machine-bench-press": {"name":"Жим лёжа в Смите","tier":"uncommon"},
  "fedb-incline-cable-chest-press": {"name":"Жим на наклонной в кроссовере","tier":"uncommon"},
  "fedb-standing-cable-chest-press": {"name":"Жим от груди в блоке стоя","tier":"uncommon"},
  "fedb-cable-chest-press": {"name":"Жим от груди в кроссовере","tier":"uncommon"},
  "fedb-leverage-chest-press": {"name":"Жим от груди в рычажном тренажёре","tier":"uncommon"},
  "fedb-decline-barbell-bench-press": {"name":"Жим штанги на скамье с отрицательным наклоном","tier":"uncommon"},
  "fedb-leverage-incline-chest-press": {"name":"Наклонный жим в рычажном тренажёре","tier":"uncommon"},
  "fedb-smith-machine-incline-bench-press": {"name":"Наклонный жим в Смите","tier":"uncommon"},
  "fedb-incline-push-up": {"name":"Отжимания на возвышении","tier":"uncommon"},
  "fedb-suspended-push-up": {"name":"Отжимания на петлях","tier":"uncommon"},
  "fedb-push-ups-with-feet-elevated": {"name":"Отжимания с ногами на возвышении","tier":"uncommon"},
  "fedb-medicine-ball-chest-pass": {"name":"Передача медбола от груди","tier":"uncommon"},
  "fedb-alternating-floor-press": {"name":"Попеременный жим с пола","tier":"uncommon"},
  "fedb-straight-arm-dumbbell-pullover": {"name":"Пуловер с гантелью прямыми руками","tier":"uncommon"},
  "fedb-bent-arm-dumbbell-pullover": {"name":"Пуловер с гантелью с согнутыми руками","tier":"uncommon"},
  "fedb-incline-dumbbell-flyes": {"name":"Разводка гантелей на наклонной","tier":"uncommon"},
  "fedb-decline-dumbbell-flyes": {"name":"Разводка гантелей на отрицательном наклоне","tier":"uncommon"},
  "fedb-flat-bench-cable-flyes": {"name":"Разводка рук в блоке лёжа","tier":"uncommon"},
  "fedb-incline-cable-flye": {"name":"Разводка рук в блоке на наклонной","tier":"uncommon"},
  "fedb-chest-and-front-of-shoulder-stretch": {"name":"Растяжка груди и передней дельты","tier":"uncommon"},
  "fedb-chest-stretch-on-stability-ball": {"name":"Растяжка груди на фитболе","tier":"uncommon"},
  "fedb-behind-head-chest-stretch": {"name":"Растяжка груди с руками за головой","tier":"uncommon"},
  "fedb-cross-over-with-bands": {"name":"Сведение рук с резиной","tier":"uncommon"},
  "fedb-low-cable-crossover": {"name":"Сведение рук снизу в кроссовере","tier":"uncommon"},
  "running-high-knees": {"name":"Бег с высоким подниманием бедра","tier":"uncommon"},
  "running-butt-kicks": {"name":"Бег с захлёстом голени","tier":"uncommon"},
  "running-bounds": {"name":"Беговые прыжки","tier":"uncommon"},
  "fedb-recumbent-bike": {"name":"Горизонтальный велотренажёр","tier":"uncommon"},
  "fedb-skating": {"name":"Конькобежный бег","tier":"uncommon"},
  "running-ankling": {"name":"Семенящий бег","tier":"uncommon"},
  "fedb-prowler-sprint": {"name":"Спринт с силовыми санями","tier":"uncommon"},
  "sled-push": {"name":"Толкание саней","tier":"uncommon"},
  "farmer-carry": {"name":"Фермерская прогулка","tier":"uncommon"},
  "fedb-side-jackknife": {"name":"Боковая складка","tier":"uncommon"},
  "fedb-one-arm-high-pulley-cable-side-bends": {"name":"Боковые наклоны одной рукой в верхнем блоке","tier":"uncommon"},
  "fedb-one-arm-medicine-ball-slam": {"name":"Бросок медбола в пол одной рукой","tier":"uncommon"},
  "fedb-ab-roller": {"name":"Выкат с роликом","tier":"uncommon"},
  "fedb-barbell-ab-rollout": {"name":"Выкат со штангой","tier":"uncommon"},
  "fedb-standing-cable-lift": {"name":"Диагональная тяга блока стоя","tier":"uncommon"},
  "vital-diagonal-kettlebell-lift": {"name":"Диагональный подъём гири","tier":"uncommon"},
  "fedb-cross-body-crunch": {"name":"Косые скручивания","tier":"uncommon"},
  "fedb-oblique-crunches": {"name":"Косые скручивания лёжа","tier":"uncommon"},
  "fedb-oblique-crunches-on-the-floor": {"name":"Косые скручивания на полу","tier":"uncommon"},
  "fedb-dumbbell-side-bend": {"name":"Наклоны в сторону с гантелью","tier":"uncommon"},
  "fedb-flutter-kicks": {"name":"Ножницы","tier":"uncommon"},
  "fedb-cable-reverse-crunch": {"name":"Обратные скручивания в блоке","tier":"uncommon"},
  "fedb-decline-reverse-crunch": {"name":"Обратные скручивания на отрицательном наклоне","tier":"uncommon"},
  "fedb-landmine-180s": {"name":"Повороты «180» с грифом","tier":"uncommon"},
  "fedb-exercise-ball-pull-in": {"name":"Подтягивание коленей на фитболе","tier":"uncommon"},
  "fedb-seated-leg-tucks": {"name":"Подтягивание коленей сидя","tier":"uncommon"},
  "fedb-leg-pull-in": {"name":"Подтягивание ног лёжа","tier":"uncommon"},
  "fedb-flat-bench-leg-pull-in": {"name":"Подтягивание ног лёжа на скамье","tier":"uncommon"},
  "fedb-seated-flat-bench-leg-pull-in": {"name":"Подтягивание ног сидя на скамье","tier":"uncommon"},
  "fedb-knee-hip-raise-on-parallel-bars": {"name":"Подъём коленей в упоре на брусьях","tier":"uncommon"},
  "fedb-sit-up": {"name":"Подъём корпуса лёжа","tier":"uncommon"},
  "fedb-hanging-leg-raise": {"name":"Подъём ног в висе","tier":"uncommon"},
  "fedb-bottoms-up": {"name":"Подъём таза лёжа","tier":"uncommon"},
  "fedb-butt-ups": {"name":"Подъём таза с прямыми ногами","tier":"uncommon"},
  "fedb-bent-knee-hip-raise": {"name":"Подъём таза с согнутыми коленями","tier":"uncommon"},
  "fedb-side-bridge": {"name":"Подъёмы таза в боковом упоре (Side Bridge)","tier":"uncommon"},
  "fedb-alternate-heel-touchers": {"name":"Попеременные касания пяток","tier":"uncommon"},
  "russian-twist": {"name":"Русский твист","tier":"uncommon"},
  "fedb-cable-russian-twists": {"name":"Русский твист в блоке","tier":"uncommon"},
  "fedb-jackknife-sit-up": {"name":"Складка «складной нож»","tier":"uncommon"},
  "fedb-cable-crunch": {"name":"Скручивания в блоке","tier":"uncommon"},
  "fedb-ab-crunch-machine": {"name":"Скручивания в тренажёре","tier":"uncommon"},
  "fedb-elbow-to-knee": {"name":"Скручивания локоть к колену","tier":"uncommon"},
  "fedb-decline-crunch": {"name":"Скручивания на скамье с отрицательным наклоном","tier":"uncommon"},
  "fedb-exercise-ball-crunch": {"name":"Скручивания на фитболе","tier":"uncommon"},
  "fedb-tuck-crunch": {"name":"Скручивания с подтягиванием коленей","tier":"uncommon"},
  "fedb-cable-seated-crunch": {"name":"Скручивания сидя в блоке","tier":"uncommon"},
  "fedb-standing-rope-crunch": {"name":"Скручивания стоя с канатом","tier":"uncommon"},
  "fedb-spider-crawl": {"name":"Шаги в планке «паук»","tier":"uncommon"},
  "fedb-barbell-side-split-squat": {"name":"Боковой сплит-присед","tier":"uncommon"},
  "fedb-lateral-cone-hops": {"name":"Боковые прыжки через конусы","tier":"uncommon"},
  "bulgarian-split-squat": {"name":"Болгарский сплит-присед со штангой","tier":"uncommon"},
  "fedb-bench-sprint": {"name":"Быстрые зашагивания на скамью","tier":"uncommon"},
  "fedb-fast-skipping": {"name":"Быстрые прыжки на месте","tier":"uncommon"},
  "fedb-barbell-walking-lunge": {"name":"Выпады в ходьбе","tier":"uncommon"},
  "fedb-dumbbell-lunges": {"name":"Выпады с гантелями","tier":"uncommon"},
  "fedb-single-leg-push-off": {"name":"Выпрыгивание с опорой одной ногой","tier":"uncommon"},
  "fedb-inchworm": {"name":"Выход руками в планку","tier":"uncommon"},
  "fedb-goblet-squat": {"name":"Гоблет-присед","tier":"uncommon"},
  "fedb-band-good-morning-pull-through": {"name":"Гудмонинг с протяжкой резины","tier":"uncommon"},
  "fedb-band-good-morning": {"name":"Гудмонинг с резиной","tier":"uncommon"},
  "fedb-groiners": {"name":"Динамическая растяжка паха в выпаде","tier":"uncommon"},
  "fedb-calf-press-on-the-leg-press-machine": {"name":"Жим носками в жиме ногами","tier":"uncommon"},
  "fedb-calf-press": {"name":"Жим носками в тренажёре","tier":"uncommon"},
  "fedb-front-box-jump": {"name":"Запрыгивание на тумбу","tier":"uncommon"},
  "fedb-barbell-step-ups": {"name":"Зашагивания со штангой","tier":"uncommon"},
  "fedb-hip-circles-prone": {"name":"Круги бедром лёжа","tier":"uncommon"},
  "vital-kettlebell-march": {"name":"Марш с гирей перед собой","tier":"uncommon"},
  "fedb-one-arm-kettlebell-swings": {"name":"Мах гири одной рукой","tier":"uncommon"},
  "fedb-reverse-hyperextension": {"name":"Обратная гиперэкстензия","tier":"uncommon"},
  "fedb-dumbbell-rear-lunge": {"name":"Обратные выпады с гантелями","tier":"uncommon"},
  "vital-barbell-reverse-lunge": {"name":"Обратные выпады со штангой","tier":"uncommon"},
  "fedb-glute-ham-raise": {"name":"Подъём корпуса на бицепс бедра","tier":"uncommon"},
  "fedb-smith-machine-calf-raise": {"name":"Подъём на носки в Смите","tier":"uncommon"},
  "fedb-calf-raises-with-bands": {"name":"Подъём на носки с резиной","tier":"uncommon"},
  "fedb-rocking-standing-calf-raise": {"name":"Подъём на носки стоя со штангой","tier":"uncommon"},
  "fedb-dumbbell-seated-one-leg-calf-raise": {"name":"Подъём на носок сидя на одной ноге с гантелью","tier":"uncommon"},
  "fedb-cable-hip-adduction": {"name":"Приведение бедра в блоке","tier":"uncommon"},
  "fedb-band-hip-adductions": {"name":"Приведение бедра с резиной","tier":"uncommon"},
  "fedb-plie-dumbbell-squat": {"name":"Присед плие с гантелью","tier":"uncommon"},
  "fedb-dumbbell-squat-to-a-bench": {"name":"Присед с гантелями на скамью","tier":"uncommon"},
  "fedb-box-squat": {"name":"Присед со штангой на тумбу","tier":"uncommon"},
  "fedb-smith-machine-squat": {"name":"Приседания в Смите","tier":"uncommon"},
  "fedb-chair-squat": {"name":"Приседания к стулу","tier":"uncommon"},
  "fedb-freehand-jump-squat": {"name":"Приседания с выпрыгиванием","tier":"uncommon"},
  "fedb-dumbbell-squat": {"name":"Приседания с гантелями","tier":"uncommon"},
  "fedb-hamstring-smr": {"name":"Прокатка задней поверхности бедра","tier":"uncommon"},
  "fedb-quadriceps-smr": {"name":"Прокатка передней поверхности бедра","tier":"uncommon"},
  "fedb-anterior-tibialis-smr": {"name":"Прокатка передней поверхности голени","tier":"uncommon"},
  "fedb-adductor": {"name":"Прокатка приводящих мышц","tier":"uncommon"},
  "fedb-foot-smr": {"name":"Прокатка стопы","tier":"uncommon"},
  "fedb-scissors-jump": {"name":"Прыжки «ножницы»","tier":"uncommon"},
  "fedb-hurdle-hops": {"name":"Прыжки через барьеры","tier":"uncommon"},
  "fedb-box-skip": {"name":"Прыжковые зашагивания на тумбу","tier":"uncommon"},
  "fedb-standing-hamstring-and-calf-stretch": {"name":"Растяжка задней поверхности бедра и икр","tier":"uncommon"},
  "fedb-chair-leg-extended-stretch": {"name":"Растяжка задней поверхности бедра на стуле","tier":"uncommon"},
  "fedb-quad-stretch": {"name":"Растяжка передней поверхности бедра стоя","tier":"uncommon"},
  "fedb-it-band-and-glute-stretch": {"name":"Растяжка ягодиц и наружной поверхности бедра","tier":"uncommon"},
  "fedb-romanian-deadlift-from-deficit": {"name":"Румынская тяга с возвышения","tier":"uncommon"},
  "fedb-hip-flexion-with-band": {"name":"Сгибание бедра с резиной","tier":"uncommon"},
  "fedb-natural-glute-ham-raise": {"name":"Сгибание корпуса на бицепс бедра с колен","tier":"uncommon"},
  "fedb-ball-leg-curl": {"name":"Сгибание ног на фитболе","tier":"uncommon"},
  "fedb-seated-leg-curl": {"name":"Сгибание ног сидя в тренажёре","tier":"uncommon"},
  "fedb-platform-hamstring-slides": {"name":"Сгибание ног со скольжением пяток","tier":"uncommon"},
  "fedb-standing-leg-curl": {"name":"Сгибание ноги стоя в тренажёре","tier":"uncommon"},
  "fedb-lying-crossover": {"name":"Скручивание лёжа для ягодиц","tier":"uncommon"},
  "fedb-smith-single-leg-split-squat": {"name":"Сплит-присед на одной ноге в Смите","tier":"uncommon"},
  "fedb-split-squat-with-dumbbells": {"name":"Сплит-присед с гантелями","tier":"uncommon"},
  "fedb-kettlebell-one-legged-deadlift": {"name":"Становая на одной ноге с гирей","tier":"uncommon"},
  "vital-smith-stiff-leg-deadlift": {"name":"Становая на прямых ногах в Смите","tier":"uncommon"},
  "fedb-stiff-legged-dumbbell-deadlift": {"name":"Становая на прямых ногах с гантелями","tier":"uncommon"},
  "fedb-cable-deadlifts": {"name":"Становая тяга в блоке","tier":"uncommon"},
  "fedb-leverage-deadlift": {"name":"Становая тяга в рычажном тренажёре","tier":"uncommon"},
  "stiff-leg-deadlift": {"name":"Становая тяга на прямых ногах со штангой","tier":"uncommon"},
  "fedb-trap-bar-deadlift": {"name":"Становая тяга с трэп-грифом","tier":"uncommon"},
  "fedb-sled-drag-harness": {"name":"Тяга саней в упряжи","tier":"uncommon"},
  "fedb-front-squats-with-two-kettlebells": {"name":"Фронтальный присед с двумя гирями","tier":"uncommon"},
  "front-squat": {"name":"Фронтальный присед со штангой","tier":"uncommon"},
  "fedb-machine-shoulder-military-press": {"name":"Армейский жим в тренажёре","tier":"uncommon"},
  "fedb-two-arm-kettlebell-military-press": {"name":"Армейский жим двух гирь","tier":"uncommon"},
  "fedb-seated-barbell-military-press": {"name":"Армейский жим сидя","tier":"uncommon"},
  "vital-smith-seated-military-press": {"name":"Армейский жим сидя в Смите","tier":"uncommon"},
  "fedb-backward-medicine-ball-throw": {"name":"Бросок медбола назад через голову","tier":"uncommon"},
  "fedb-medicine-ball-scoop-throw": {"name":"Бросок медбола снизу вверх","tier":"uncommon"},
  "fedb-external-rotation-with-cable": {"name":"Внешняя ротация плеча в блоке","tier":"uncommon"},
  "fedb-external-rotation": {"name":"Внешняя ротация плеча с гантелью","tier":"uncommon"},
  "fedb-cable-internal-rotation": {"name":"Внутренняя ротация плеча в блоке","tier":"uncommon"},
  "fedb-internal-rotation-with-band": {"name":"Внутренняя ротация плеча с резинкой","tier":"uncommon"},
  "fedb-battling-ropes": {"name":"Волны с канатами","tier":"uncommon"},
  "fedb-arnold-dumbbell-press": {"name":"Жим Арнольда","tier":"uncommon"},
  "seated-dumbbell-press": {"name":"Жим гантелей сидя","tier":"uncommon"},
  "vital-single-arm-kettlebell-press": {"name":"Жим гири одной рукой стоя","tier":"uncommon"},
  "fedb-kettlebell-seated-press": {"name":"Жим гирь сидя","tier":"uncommon"},
  "fedb-cable-shoulder-press": {"name":"Жим над головой в блоке","tier":"uncommon"},
  "fedb-smith-machine-overhead-shoulder-press": {"name":"Жим над головой в Смите","tier":"uncommon"},
  "fedb-shoulder-press-with-bands": {"name":"Жим над головой с резиной","tier":"uncommon"},
  "fedb-seated-cable-shoulder-press": {"name":"Жим над головой сидя в блоке","tier":"uncommon"},
  "fedb-barbell-shoulder-press": {"name":"Жим штанги от плеч","tier":"uncommon"},
  "fedb-landmine-linear-jammer": {"name":"Линейный жим грифа из угла","tier":"uncommon"},
  "fedb-dumbbell-scaption": {"name":"Подъём гантелей в плоскости лопаток","tier":"uncommon"},
  "fedb-dumbbell-raise": {"name":"Подъём гантелей вперёд","tier":"uncommon"},
  "vital-plate-front-raise": {"name":"Подъём диска перед собой","tier":"uncommon"},
  "fedb-front-cable-raise": {"name":"Подъём руки перед собой в блоке","tier":"uncommon"},
  "vital-cable-cross-lateral-raise": {"name":"Разведение рук в кроссовере стоя","tier":"uncommon"},
  "fedb-lateral-raise-with-bands": {"name":"Разведение рук в стороны с резинкой","tier":"uncommon"},
  "vital-machine-lateral-raise": {"name":"Разведение рук в тренажёре на среднюю дельту","tier":"uncommon"},
  "fedb-band-pull-apart": {"name":"Разведение рук с резиной","tier":"uncommon"},
  "fedb-cable-seated-lateral-raise": {"name":"Разведение рук сидя в блоке","tier":"uncommon"},
  "fedb-bent-over-low-pulley-side-lateral": {"name":"Разведение руки в наклоне в нижнем блоке","tier":"uncommon"},
  "fedb-back-flyes-with-bands": {"name":"Разведения на заднюю дельту с резиной","tier":"uncommon"},
  "fedb-cable-rear-delt-fly": {"name":"Разводка на заднюю дельту в блоке","tier":"uncommon"},
  "fedb-kettlebell-thruster": {"name":"Трастер с гирями","tier":"uncommon"},
  "fedb-standing-dumbbell-upright-row": {"name":"Тяга гантелей к подбородку стоя","tier":"uncommon"},
  "fedb-smith-machine-upright-row": {"name":"Тяга к подбородку в Смите","tier":"uncommon"},
  "fedb-upright-row-with-bands": {"name":"Тяга к подбородку с резиной","tier":"uncommon"},
  "fedb-cable-rope-rear-delt-rows": {"name":"Тяга каната на заднюю дельту","tier":"uncommon"},
  "fedb-barbell-rear-delt-row": {"name":"Тяга на заднюю дельту в наклоне","tier":"uncommon"},
  "fedb-upright-cable-row": {"name":"Тяга нижнего блока к подбородку","tier":"uncommon"},
  "fedb-low-pulley-row-to-neck": {"name":"Тяга нижнего блока к шее","tier":"uncommon"},
  "upright-row": {"name":"Тяга штанги к подбородку","tier":"uncommon"},
  "fedb-cable-shrugs": {"name":"Шраги в блоке","tier":"uncommon"},
  "fedb-leverage-shrug": {"name":"Шраги в рычажном тренажёре","tier":"uncommon"},
  "fedb-dumbbell-shrug": {"name":"Шраги с гантелями","tier":"uncommon"},
  "shrugs": {"name":"Шраги со штангой","tier":"uncommon"},
  "fedb-dumbbell-floor-press": {"name":"Жим гантелей с пола","tier":"uncommon"},
  "fedb-close-grip-barbell-bench-press": {"name":"Жим лёжа узким хватом","tier":"uncommon"},
  "fedb-floor-press": {"name":"Жим с пола","tier":"uncommon"},
  "fedb-smith-machine-close-grip-bench-press": {"name":"Жим узким хватом в Смите","tier":"uncommon"},
  "fedb-concentration-curls": {"name":"Концентрированный подъём на бицепс","tier":"uncommon"},
  "fedb-wrist-circles": {"name":"Круговые движения кистями","tier":"uncommon"},
  "fedb-brachialis-smr": {"name":"Массаж плечевой мышцы на валике","tier":"uncommon"},
  "fedb-cable-hammer-curls-rope-attachment": {"name":"Молоток на блоке с канатом","tier":"uncommon"},
  "fedb-incline-hammer-curls": {"name":"Молоток на наклонной скамье","tier":"uncommon"},
  "fedb-preacher-hammer-dumbbell-curl": {"name":"Молоток на скамье Скотта","tier":"uncommon"},
  "fedb-bench-dips": {"name":"Обратные отжимания от скамьи","tier":"uncommon"},
  "fedb-dip-machine": {"name":"Отжимания в тренажёре","tier":"uncommon"},
  "close-grip-push-up": {"name":"Отжимания узким хватом","tier":"uncommon"},
  "fedb-incline-dumbbell-curl": {"name":"Подъём гантелей на бицепс на наклонной","tier":"uncommon"},
  "fedb-seated-dumbbell-curl": {"name":"Подъём гантелей на бицепс сидя","tier":"uncommon"},
  "fedb-one-arm-dumbbell-preacher-curl": {"name":"Подъём гантели на скамье Скотта одной рукой","tier":"uncommon"},
  "fedb-high-cable-curls": {"name":"Подъём на бицепс в верхнем блоке","tier":"uncommon"},
  "fedb-machine-bicep-curl": {"name":"Подъём на бицепс в тренажёре","tier":"uncommon"},
  "fedb-cable-preacher-curl": {"name":"Подъём на бицепс на скамье Скотта в блоке","tier":"uncommon"},
  "fedb-machine-preacher-curls": {"name":"Подъём на бицепс на скамье Скотта в тренажёре","tier":"uncommon"},
  "fedb-reverse-cable-curl": {"name":"Подъём на бицепс обратным хватом в блоке","tier":"uncommon"},
  "fedb-barbell-curls-lying-against-an-incline": {"name":"Подъём штанги на бицепс лёжа на наклонной","tier":"uncommon"},
  "fedb-reverse-barbell-curl": {"name":"Подъём штанги на бицепс обратным хватом","tier":"uncommon"},
  "fedb-preacher-curl": {"name":"Подъём штанги на скамье Скотта","tier":"uncommon"},
  "fedb-ez-bar-curl": {"name":"Подъём EZ-грифа на бицепс","tier":"uncommon"},
  "fedb-decline-dumbbell-triceps-extension": {"name":"Разгибание гантелей на трицепс вниз головой","tier":"uncommon"},
  "fedb-seated-bent-over-one-arm-dumbbell-triceps-extension": {"name":"Разгибание гантели на трицепс сидя в наклоне","tier":"uncommon"},
  "fedb-dumbbell-one-arm-triceps-extension": {"name":"Разгибание гантели одной рукой из-за головы","tier":"uncommon"},
  "fedb-palms-down-dumbbell-wrist-curl-over-a-bench": {"name":"Разгибание запястий с гантелями на скамье","tier":"uncommon"},
  "fedb-seated-dumbbell-palms-down-wrist-curl": {"name":"Разгибание запястий с гантелями сидя","tier":"uncommon"},
  "fedb-palms-down-wrist-curl-over-a-bench": {"name":"Разгибание запястий со штангой на скамье","tier":"uncommon"},
  "fedb-machine-triceps-extension": {"name":"Разгибание на трицепс в тренажёре","tier":"uncommon"},
  "fedb-cable-lying-triceps-extension": {"name":"Разгибание на трицепс лёжа в блоке","tier":"uncommon"},
  "fedb-body-tricep-press": {"name":"Разгибание на трицепс с весом тела","tier":"uncommon"},
  "fedb-band-skull-crusher": {"name":"Разгибание на трицепс с резиной лёжа","tier":"uncommon"},
  "fedb-body-up": {"name":"Разгибание рук с весом тела","tier":"uncommon"},
  "fedb-decline-ez-bar-triceps-extension": {"name":"Разгибание EZ-грифа на трицепс вниз головой","tier":"uncommon"},
  "fedb-overhead-triceps": {"name":"Растяжка трицепса над головой","tier":"uncommon"},
  "fedb-cable-wrist-curl": {"name":"Сгибание запястий в блоке","tier":"uncommon"},
  "fedb-palms-up-dumbbell-wrist-curl-over-a-bench": {"name":"Сгибание запястий с гантелями на скамье","tier":"uncommon"},
  "fedb-palms-up-barbell-wrist-curl-over-a-bench": {"name":"Сгибание запястий со штангой на скамье","tier":"uncommon"},
  "fedb-lying-cable-curl": {"name":"Сгибание рук лёжа в блоке","tier":"uncommon"},
  "fedb-overhead-cable-curl": {"name":"Сгибание рук над головой в блоках","tier":"uncommon"},
  "french-press": {"name":"Французский жим с EZ-грифом","tier":"uncommon"},
  "fedb-superman": {"name":"«Супермен» лёжа","tier":"uncommon"},
  "fedb-overhead-slam": {"name":"Бросок медбола в пол над головой","tier":"uncommon"},
  "fedb-leverage-high-row": {"name":"Верхняя тяга в рычажном тренажёре","tier":"uncommon"},
  "fedb-hyperextensions-with-no-hyperextension-bench": {"name":"Гиперэкстензия без скамьи","tier":"uncommon"},
  "fedb-weighted-ball-hyperextension": {"name":"Гиперэкстензия на фитболе с весом","tier":"uncommon"},
  "fedb-bodyweight-mid-row": {"name":"Горизонтальная тяга с весом тела — уточнить опору","tier":"uncommon"},
  "fedb-stiff-leg-barbell-good-morning": {"name":"Гудмонинг на прямых ногах","tier":"uncommon"},
  "good-morning": {"name":"Гудмонинг со штангой","tier":"uncommon"},
  "fedb-rope-climb": {"name":"Лазание по канату","tier":"uncommon"},
  "fedb-catch-and-overhead-throw": {"name":"Ловля и бросок медбола над головой","tier":"uncommon"},
  "fedb-rhomboids-smr": {"name":"Прокатка ромбовидных мышц","tier":"uncommon"},
  "fedb-latissimus-dorsi-smr": {"name":"Прокатка широчайших мышц","tier":"uncommon"},
  "fedb-straight-arm-pulldown": {"name":"Пуловер прямыми руками в блоке","tier":"uncommon"},
  "fedb-cable-incline-pushdown": {"name":"Пуловер прямыми руками в наклоне в блоке","tier":"uncommon"},
  "fedb-bent-arm-barbell-pullover": {"name":"Пуловер со штангой с согнутыми руками","tier":"uncommon"},
  "fedb-elevated-cable-rows": {"name":"Тяга блока с возвышения","tier":"uncommon"},
  "fedb-smith-machine-bent-over-row": {"name":"Тяга в наклоне в Смите","tier":"uncommon"},
  "fedb-one-arm-lat-pulldown": {"name":"Тяга верхнего блока одной рукой","tier":"uncommon"},
  "fedb-kneeling-single-arm-high-pulley-row": {"name":"Тяга верхнего блока одной рукой с колен","tier":"uncommon"},
  "fedb-kneeling-high-pulley-row": {"name":"Тяга верхнего блока с колен","tier":"uncommon"},
  "fedb-dumbbell-incline-row": {"name":"Тяга гантелей лёжа на наклонной","tier":"uncommon"},
  "fedb-one-arm-kettlebell-row": {"name":"Тяга гири одной рукой","tier":"uncommon"},
  "fedb-bent-over-two-dumbbell-row": {"name":"Тяга двух гантелей в наклоне","tier":"uncommon"},
  "fedb-two-arm-kettlebell-row": {"name":"Тяга двух гирь в наклоне","tier":"uncommon"},
  "fedb-straight-bar-bench-mid-rows": {"name":"Тяга к скамье прямым грифом","tier":"uncommon"},
  "fedb-seated-one-arm-cable-pulley-rows": {"name":"Тяга нижнего блока одной рукой сидя","tier":"uncommon"},
  "fedb-bent-over-two-arm-long-bar-row": {"name":"Тяга Т-грифа двумя руками","tier":"uncommon"},
  "fedb-lying-t-bar-row": {"name":"Тяга Т-грифа лёжа","tier":"uncommon"},
  "fedb-t-bar-row-with-handle": {"name":"Тяга Т-грифа с рукоятью","tier":"uncommon"},
  "fedb-incline-bench-pull": {"name":"Тяга штанги лёжа на наклонной","tier":"uncommon"},
  "fedb-middle-back-shrug": {"name":"Шраги лёжа на середину спины","tier":"uncommon"},
  "fedb-step-up-with-knee-raise": {"name":"Зашагивание с подъёмом колена","tier":"uncommon"},
  "fedb-piriformis-smr": {"name":"Массаж грушевидной мышцы на валике","tier":"uncommon"},
  "fedb-glute-kickback": {"name":"Махи ногой назад","tier":"uncommon"},
  "fedb-leg-lift": {"name":"Подъём ноги назад","tier":"uncommon"},
  "fedb-hip-lift-with-band": {"name":"Подъём таза с резиной","tier":"uncommon"},
  "fedb-pull-through": {"name":"Протяжка между ног в блоке","tier":"uncommon"},
  "fedb-hip-extension-with-bands": {"name":"Разгибание бедра с резиной","tier":"uncommon"},
  "fedb-lying-glute": {"name":"Растяжка ягодичных лёжа","tier":"uncommon"},
  "fedb-seated-glute": {"name":"Растяжка ягодичных сидя","tier":"uncommon"},
  "fedb-barbell-glute-bridge": {"name":"Ягодичный мост со штангой на полу","tier":"uncommon"},
  "fedb-single-leg-glute-bridge": {"name":"Ягодичный мостик на одной ноге","tier":"uncommon"},
  "fedb-physioball-hip-bridge": {"name":"Ягодичный мостик на фитболе","tier":"uncommon"},
  "fedb-extended-range-one-arm-kettlebell-floor-press": {"name":"Жим гири с пола одной рукой в увеличенной амплитуде","tier":"rare"},
  "fedb-leg-over-floor-press": {"name":"Жим гири с пола с переносом ноги","tier":"rare"},
  "fedb-bench-press-with-bands": {"name":"Жим лёжа с резиной","tier":"rare"},
  "fedb-bench-press-with-chains": {"name":"Жим лёжа с цепями","tier":"rare"},
  "fedb-leverage-decline-chest-press": {"name":"Жим от груди вниз в рычажном тренажёре","tier":"rare"},
  "fedb-svend-press": {"name":"Жим Свенда","tier":"rare"},
  "fedb-isometric-wipers": {"name":"Изометрические разведения рук лёжа","tier":"rare"},
  "fedb-isometric-chest-squeezes": {"name":"Изометрическое сжатие ладоней перед грудью","tier":"rare"},
  "fedb-around-the-worlds": {"name":"Круговые разведения гантелей лёжа","tier":"rare"},
  "fedb-push-up-to-side-plank": {"name":"Отжимание с переходом в боковую планку","tier":"rare"},
  "fedb-clock-push-up": {"name":"Отжимания «по часам»","tier":"rare"},
  "fedb-single-arm-push-up": {"name":"Отжимания на одной руке","tier":"rare"},
  "fedb-push-ups-with-feet-on-an-exercise-ball": {"name":"Отжимания с ногами на фитболе","tier":"rare"},
  "fedb-plyo-push-up": {"name":"Плиометрические отжимания","tier":"rare"},
  "fedb-plyo-kettlebell-pushups": {"name":"Плиометрические отжимания на гирях","tier":"rare"},
  "fedb-front-raise-and-pullover": {"name":"Подъём вперёд с пуловером","tier":"rare"},
  "fedb-wide-grip-decline-barbell-pullover": {"name":"Пуловер со штангой широким хватом вниз головой","tier":"rare"},
  "fedb-cable-iron-cross": {"name":"Сведение рук крест-накрест в блоках","tier":"rare"},
  "fedb-forward-drag-with-press": {"name":"Тяга саней вперёд с жимом","tier":"rare"},
  "fedb-kettlebell-windmill": {"name":"«Мельница» с гирей","tier":"rare"},
  "fedb-double-kettlebell-windmill": {"name":"«Мельница» с двумя гирями","tier":"rare"},
  "fedb-cable-judo-flip": {"name":"Бросок дзюдо в блоке","tier":"rare"},
  "fedb-medicine-ball-full-twist": {"name":"Бросок медбола с полным разворотом","tier":"rare"},
  "fedb-stomach-vacuum": {"name":"Вакуум живота","tier":"rare"},
  "fedb-kettlebell-figure-8": {"name":"Восьмёрка с гирей между ног","tier":"rare"},
  "fedb-barbell-ab-rollout-on-knees": {"name":"Выкат со штангой с колен","tier":"rare"},
  "fedb-barbell-rollout-from-bench": {"name":"Выкат со штангой со скамьи","tier":"rare"},
  "fedb-bent-press": {"name":"Жим гири в наклоне","tier":"rare"},
  "fedb-pallof-press-with-rotation": {"name":"Жим Паллоффа с поворотом","tier":"rare"},
  "fedb-decline-oblique-crunch": {"name":"Косые скручивания на отрицательном наклоне","tier":"rare"},
  "fedb-barbell-side-bend": {"name":"Наклоны в сторону со штангой","tier":"rare"},
  "fedb-kettlebell-pass-between-the-legs": {"name":"Передача гири между ног","tier":"rare"},
  "fedb-spell-caster": {"name":"Повороты корпуса с гантелью","tier":"rare"},
  "fedb-seated-barbell-twist": {"name":"Повороты корпуса сидя со штангой","tier":"rare"},
  "fedb-gorilla-chin-crunch": {"name":"Подтягивание со скручиванием","tier":"rare"},
  "fedb-frog-sit-ups": {"name":"Подъём корпуса «лягушка»","tier":"rare"},
  "fedb-janda-sit-up": {"name":"Подъём корпуса по Янде","tier":"rare"},
  "fedb-press-sit-up": {"name":"Подъём корпуса с жимом штанги","tier":"rare"},
  "fedb-hanging-pike": {"name":"Подъём прямых ног в висе","tier":"rare"},
  "fedb-smith-machine-hip-raise": {"name":"Подъём таза в Смите","tier":"rare"},
  "fedb-advanced-kettlebell-windmill": {"name":"Продвинутая «мельница» с гирей","tier":"rare"},
  "fedb-cocoons": {"name":"Складка лёжа «кокон»","tier":"rare"},
  "fedb-bosu-ball-cable-crunch-with-side-bends": {"name":"Скручивания в блоке на босу с наклонами","tier":"rare"},
  "fedb-kneeling-cable-crunch-with-alternating-oblique-twists": {"name":"Скручивания в блоке с колен с поворотом","tier":"rare"},
  "fedb-sledgehammer-swings": {"name":"Удары кувалдой по покрышке","tier":"rare"},
  "fedb-wind-sprints": {"name":"Wind Sprints — уточнить перевод и технику","tier":"rare"},
  "fedb-balance-board": {"name":"Баланс на балансировочной доске","tier":"rare"},
  "fedb-one-arm-side-deadlift": {"name":"Боковая становая тяга одной рукой","tier":"rare"},
  "fedb-lateral-box-jump": {"name":"Боковое запрыгивание на тумбу","tier":"rare"},
  "fedb-side-to-side-box-shuffle": {"name":"Боковые переступания через тумбу","tier":"rare"},
  "fedb-lateral-bound": {"name":"Боковые прыжки с ноги на ногу","tier":"rare"},
  "fedb-vertical-swing": {"name":"Вертикальный мах гантелью","tier":"rare"},
  "fedb-dumbbell-clean": {"name":"Взятие гантелей на грудь","tier":"rare"},
  "fedb-one-arm-kettlebell-clean": {"name":"Взятие гири на грудь одной рукой","tier":"rare"},
  "fedb-kettlebell-dead-clean": {"name":"Взятие гири на грудь с пола","tier":"rare"},
  "fedb-open-palm-kettlebell-clean": {"name":"Взятие гири открытой ладонью","tier":"rare"},
  "fedb-one-arm-open-palm-kettlebell-clean": {"name":"Взятие гири открытой ладонью одной рукой","tier":"rare"},
  "fedb-kettlebell-hang-clean": {"name":"Взятие гири с виса","tier":"rare"},
  "fedb-clean-from-blocks": {"name":"Взятие на грудь с блоков","tier":"rare"},
  "fedb-hang-clean": {"name":"Взятие на грудь с виса","tier":"rare"},
  "fedb-hang-clean-below-the-knees": {"name":"Взятие на грудь с виса ниже колен","tier":"rare"},
  "fedb-clean": {"name":"Взятие штанги на грудь","tier":"rare"},
  "fedb-lunge-pass-through": {"name":"Выпад с передачей гири под ногой","tier":"rare"},
  "fedb-barbell-hack-squat": {"name":"Гакк-присед со штангой","tier":"rare"},
  "fedb-good-morning-off-pins": {"name":"Гудмонинг со стоек","tier":"rare"},
  "fedb-smith-machine-leg-press": {"name":"Жим ногами в Смите","tier":"rare"},
  "vital-barbell-march": {"name":"Марш со штангой на плечах","tier":"rare"},
  "fedb-bear-crawl-sled-drags": {"name":"Медвежья ходьба с санями","tier":"rare"},
  "fedb-elevated-back-lunge": {"name":"Обратный выпад с возвышения","tier":"rare"},
  "fedb-tire-flip": {"name":"Переворот покрышки","tier":"rare"},
  "fedb-conans-wheel": {"name":"Переноска «Колесо Конана»","tier":"rare"},
  "fedb-sandbag-load": {"name":"Подъём мешка на платформу","tier":"rare"},
  "fedb-donkey-calf-raises": {"name":"Подъём на носки в наклоне","tier":"rare"},
  "fedb-barbell-seated-calf-raise": {"name":"Подъём на носки сидя со штангой","tier":"rare"},
  "fedb-alternating-hang-clean": {"name":"Попеременное взятие гирь с виса","tier":"rare"},
  "fedb-double-kettlebell-alternating-hang-clean": {"name":"Попеременное взятие двух гирь с виса","tier":"rare"},
  "fedb-smith-machine-pistol-squat": {"name":"Присед «пистолет» в Смите","tier":"rare"},
  "fedb-kettlebell-pistol-squat": {"name":"Присед «пистолет» с гирей","tier":"rare"},
  "fedb-jefferson-squats": {"name":"Присед Джефферсона","tier":"rare"},
  "fedb-lying-machine-squat": {"name":"Присед лёжа в тренажёре","tier":"rare"},
  "fedb-one-leg-barbell-squat": {"name":"Присед на одной ноге со штангой","tier":"rare"},
  "fedb-reverse-band-box-squat": {"name":"Присед на тумбу с обратной резиной","tier":"rare"},
  "fedb-box-squat-with-bands": {"name":"Присед на тумбу с резиной","tier":"rare"},
  "fedb-box-squat-with-chains": {"name":"Присед на тумбу с цепями","tier":"rare"},
  "vital-dumbbell-jump-squat": {"name":"Присед с гантелями и прыжком","tier":"rare"},
  "fedb-one-arm-overhead-kettlebell-squats": {"name":"Присед с гирей над головой одной рукой","tier":"rare"},
  "fedb-barbell-squat-to-a-bench": {"name":"Присед со штангой на скамью","tier":"rare"},
  "fedb-overhead-squat": {"name":"Присед со штангой над головой","tier":"rare"},
  "fedb-frankenstein-squat": {"name":"Присед Франкенштейна","tier":"rare"},
  "fedb-yoke-walk": {"name":"Прогулка с коромыслом","tier":"rare"},
  "fedb-split-jump": {"name":"Прыжки в выпаде","tier":"rare"},
  "fedb-star-jump": {"name":"Прыжок «звезда»","tier":"rare"},
  "fedb-depth-jump-leap": {"name":"Прыжок в глубину с выпрыгиванием","tier":"rare"},
  "fedb-standing-long-jump": {"name":"Прыжок в длину с места","tier":"rare"},
  "fedb-rocket-jump": {"name":"Прыжок вверх из полуприседа","tier":"rare"},
  "fedb-double-leg-butt-kick": {"name":"Прыжок с захлёстом двух ног","tier":"rare"},
  "fedb-knee-tuck-jump": {"name":"Прыжок с подтягиванием коленей","tier":"rare"},
  "fedb-snatch-deadlift": {"name":"Рывковая становая тяга (Snatch Deadlift)","tier":"rare"},
  "fedb-snatch-pull": {"name":"Рывковая тяга с подрывом (Snatch Pull)","tier":"rare"},
  "fedb-snatch-balance": {"name":"Рывковый уход в сед","tier":"rare"},
  "fedb-snatch-from-blocks": {"name":"Рывок с блоков","tier":"rare"},
  "fedb-hang-snatch": {"name":"Рывок с виса","tier":"rare"},
  "fedb-hang-snatch-below-knees": {"name":"Рывок с виса ниже колен","tier":"rare"},
  "fedb-snatch": {"name":"Рывок штанги","tier":"rare"},
  "fedb-single-leg-hop-progression": {"name":"Серия прыжков на одной ноге","tier":"rare"},
  "fedb-power-stairs": {"name":"Силовая лестница с грузом","tier":"rare"},
  "fedb-power-clean-from-blocks": {"name":"Силовое взятие с блоков","tier":"rare"},
  "fedb-smith-machine-hang-power-clean": {"name":"Силовое взятие с виса в Смите","tier":"rare"},
  "fedb-power-clean": {"name":"Силовое взятие штанги на грудь","tier":"rare"},
  "fedb-reverse-band-power-squat": {"name":"Силовой присед с обратной резиной","tier":"rare"},
  "fedb-power-snatch": {"name":"Силовой рывок","tier":"rare"},
  "fedb-muscle-snatch": {"name":"Силовой рывок без подседа","tier":"rare"},
  "fedb-power-snatch-from-blocks": {"name":"Силовой рывок с блоков","tier":"rare"},
  "fedb-power-jerk": {"name":"Силовой швунг","tier":"rare"},
  "fedb-lunge-sprint": {"name":"Спринтерский выпад в тренажёре","tier":"rare"},
  "fedb-clean-deadlift": {"name":"Становая тяга для взятия на грудь (Clean Deadlift)","tier":"rare"},
  "fedb-rickshaw-deadlift": {"name":"Становая тяга с рамой","tier":"rare"},
  "fedb-reverse-band-sumo-deadlift": {"name":"Становая тяга сумо с обратной резиной","tier":"rare"},
  "fedb-split-jerk": {"name":"Толчок в ножницы","tier":"rare"},
  "fedb-car-deadlift": {"name":"Тяга автомобиля на раме (Car Deadlift)","tier":"rare"},
  "fedb-clean-pull": {"name":"Тяга для взятия на грудь с подрывом (Clean Pull)","tier":"rare"},
  "fedb-front-barbell-squat-to-a-bench": {"name":"Фронтальный присед на скамью","tier":"rare"},
  "fedb-iron-cross": {"name":"«Железный крест» с гантелями","tier":"rare"},
  "fedb-anti-gravity-press": {"name":"Антигравитационный жим","tier":"rare"},
  "fedb-two-arm-kettlebell-clean": {"name":"Взятие двух гирь на грудь","tier":"rare"},
  "fedb-one-arm-kettlebell-clean-and-jerk": {"name":"Взятие и толчок гири одной рукой","tier":"rare"},
  "fedb-clean-and-press": {"name":"Взятие штанги на грудь и жим","tier":"rare"},
  "fedb-car-drivers": {"name":"Вращение блина перед собой","tier":"rare"},
  "fedb-kettlebell-arnold-press": {"name":"Жим Арнольда с гирями","tier":"rare"},
  "fedb-bradford-rocky-presses": {"name":"Жим Брэдфорда","tier":"rare"},
  "fedb-standing-bradford-press": {"name":"Жим Брэдфорда стоя","tier":"rare"},
  "fedb-one-arm-kettlebell-military-press-to-the-side": {"name":"Жим гири одной рукой в сторону","tier":"rare"},
  "fedb-circus-bell": {"name":"Жим цирковой гантели","tier":"rare"},
  "fedb-push-press": {"name":"Жимовой швунг","tier":"rare"},
  "fedb-cuban-press": {"name":"Кубинский жим","tier":"rare"},
  "fedb-single-arm-linear-jammer": {"name":"Линейный жим грифа одной рукой","tier":"rare"},
  "fedb-kettlebell-pirate-ships": {"name":"Маятник с гирей","tier":"rare"},
  "fedb-handstand-push-ups": {"name":"Отжимания в стойке на руках","tier":"rare"},
  "fedb-one-arm-kettlebell-para-press": {"name":"Пара-жим гири одной рукой","tier":"rare"},
  "fedb-log-lift": {"name":"Подъём и жим бревна","tier":"rare"},
  "fedb-barbell-incline-shoulder-raise": {"name":"Подъём плеч на наклонной","tier":"rare"},
  "fedb-dumbbell-incline-shoulder-raise": {"name":"Подъём плеч с гантелями на наклонной","tier":"rare"},
  "fedb-see-saw-press-alternating-side-press": {"name":"Попеременный жим гантелей «качели»","tier":"rare"},
  "fedb-kettlebell-seesaw-press": {"name":"Попеременный жим гирь «качели»","tier":"rare"},
  "fedb-alternating-deltoid-raise": {"name":"Попеременный подъём гантелей на дельты","tier":"rare"},
  "fedb-one-arm-kettlebell-split-snatch": {"name":"Рывок гири в разножку","tier":"rare"},
  "fedb-one-arm-kettlebell-snatch": {"name":"Рывок гири одной рукой","tier":"rare"},
  "fedb-double-kettlebell-snatch": {"name":"Рывок двух гирь","tier":"rare"},
  "fedb-one-arm-kettlebell-split-jerk": {"name":"Толчок гири в разножку","tier":"rare"},
  "fedb-two-arm-kettlebell-jerk": {"name":"Толчок гири двумя руками","tier":"rare"},
  "fedb-one-arm-kettlebell-jerk": {"name":"Толчок гири одной рукой","tier":"rare"},
  "fedb-double-kettlebell-jerk": {"name":"Толчок двух гирь","tier":"rare"},
  "fedb-clean-and-jerk": {"name":"Толчок штанги","tier":"rare"},
  "fedb-kettlebell-turkish-get-up-lunge-style": {"name":"Турецкий подъём с гирей через выпад","tier":"rare"},
  "fedb-kettlebell-turkish-get-up-squat-style": {"name":"Турецкий подъём с гирей через присед","tier":"rare"},
  "fedb-kettlebell-sumo-high-pull": {"name":"Тяга гири сумо к подбородку","tier":"rare"},
  "fedb-crucifix": {"name":"Удержание веса в стороны","tier":"rare"},
  "fedb-one-arm-kettlebell-push-press": {"name":"Швунг жимовой с гирей одной рукой","tier":"rare"},
  "fedb-double-kettlebell-push-press": {"name":"Швунг жимовой с двумя гирями","tier":"rare"},
  "fedb-calf-machine-shoulder-shrug": {"name":"Шраги в тренажёре для икр","tier":"rare"},
  "fedb-clean-shrug": {"name":"Шраги в тяге для взятия","tier":"rare"},
  "fedb-barbell-shrug-behind-the-back": {"name":"Шраги со штангой за спиной","tier":"rare"},
  "fedb-bottoms-up-clean-from-the-hang-position": {"name":"Взятие гири донышком вверх с виса","tier":"rare"},
  "fedb-close-grip-dumbbell-press": {"name":"Жим гантелей узким хватом","tier":"rare"},
  "fedb-jm-press": {"name":"Жим Джей-Эм","tier":"rare"},
  "fedb-reverse-triceps-bench-press": {"name":"Жим лёжа обратным хватом на трицепс","tier":"rare"},
  "fedb-reverse-band-bench-press": {"name":"Жим лёжа с обратной резиной","tier":"rare"},
  "fedb-board-press": {"name":"Жим с бруска","tier":"rare"},
  "fedb-one-arm-floor-press": {"name":"Жим с пола одной рукой","tier":"rare"},
  "fedb-floor-press-with-chains": {"name":"Жим с пола с цепями","tier":"rare"},
  "fedb-pin-presses": {"name":"Жим со стоек с ограниченной амплитудой","tier":"rare"},
  "fedb-close-grip-ez-bar-press": {"name":"Жим EZ-грифа узким хватом","tier":"rare"},
  "fedb-ring-dips": {"name":"Отжимания на кольцах","tier":"rare"},
  "fedb-lying-supine-dumbbell-curl": {"name":"Подъём гантелей на бицепс лёжа","tier":"rare"},
  "fedb-lying-close-grip-bar-curl-on-high-pulley": {"name":"Подъём на бицепс лёжа в верхнем блоке","tier":"rare"},
  "fedb-close-grip-ez-bar-curl-with-band": {"name":"Подъём на бицепс узким хватом с резиной","tier":"rare"},
  "fedb-rickshaw-carry": {"name":"Прогулка с рамой","tier":"rare"},
  "fedb-dumbbell-lying-pronation": {"name":"Пронация предплечья с гантелью лёжа","tier":"rare"},
  "fedb-drag-curl": {"name":"Протягивающий подъём на бицепс","tier":"rare"},
  "fedb-one-arm-supinated-dumbbell-triceps-extension": {"name":"Разгибание гантели на трицепс обратным хватом одной рукой","tier":"rare"},
  "fedb-dumbbell-tricep-extension-pronated-grip": {"name":"Разгибание гантели на трицепс прямым хватом","tier":"rare"},
  "fedb-one-arm-pronated-dumbbell-triceps-extension": {"name":"Разгибание гантели на трицепс прямым хватом одной рукой","tier":"rare"},
  "fedb-cable-incline-triceps-extension": {"name":"Разгибание на трицепс в наклоне в блоке","tier":"rare"},
  "fedb-low-cable-triceps-extension": {"name":"Разгибание на трицепс в нижнем блоке","tier":"rare"},
  "fedb-kneeling-cable-triceps-extension": {"name":"Разгибание рук на трицепс с колен в блоке","tier":"rare"},
  "fedb-finger-curls": {"name":"Сгибание пальцами со штангой","tier":"rare"},
  "fedb-dumbbell-lying-supination": {"name":"Супинация предплечья с гантелью лёжа","tier":"rare"},
  "fedb-plate-pinch": {"name":"Удержание блинов пальцами","tier":"rare"},
  "fedb-decline-close-grip-bench-to-skull-crusher": {"name":"Французский жим узким хватом на наклоне","tier":"rare"},
  "fedb-one-handed-hang": {"name":"Вис на одной руке","tier":"rare"},
  "fedb-muscle-up": {"name":"Выход силой на перекладине","tier":"rare"},
  "fedb-kipping-muscle-up": {"name":"Выход силой с махом","tier":"rare"},
  "fedb-seated-good-mornings": {"name":"Гудмонинг сидя","tier":"rare"},
  "fedb-lower-back-smr": {"name":"Мягкая прокатка поясницы","tier":"rare"},
  "fedb-gironda-sternum-chins": {"name":"Подтягивания Жиронды к груди","tier":"rare"},
  "fedb-one-arm-chin-up": {"name":"Подтягивания на одной руке","tier":"rare"},
  "fedb-keg-load": {"name":"Подъём бочонка на платформу","tier":"rare"},
  "fedb-atlas-stones": {"name":"Подъём камня Атласа","tier":"rare"},
  "fedb-atlas-stone-trainer": {"name":"Подъём тренировочного камня Атласа","tier":"rare"},
  "fedb-alternating-renegade-row": {"name":"Попеременная тяга гирь в планке","tier":"rare"},
  "fedb-axle-deadlift": {"name":"Становая тяга с аксель-грифом","tier":"rare"},
  "fedb-deficit-deadlift": {"name":"Становая тяга с дефицита","tier":"rare"},
  "fedb-reverse-band-deadlift": {"name":"Становая тяга с обратной резиной","tier":"rare"},
  "fedb-deadlift-with-bands": {"name":"Становая тяга с резиной","tier":"rare"},
  "fedb-deadlift-with-chains": {"name":"Становая тяга с цепями","tier":"rare"},
  "fedb-lying-cambered-barbell-row": {"name":"Тяга изогнутого грифа лёжа","tier":"rare"},
  "fedb-shotgun-row": {"name":"Тяга одной рукой в блоке","tier":"rare"},
  "fedb-rack-pulls": {"name":"Тяга с плинтов","tier":"rare"},
  "fedb-rack-pull-with-bands": {"name":"Тяга с плинтов с резиной","tier":"rare"},
  "fedb-sled-row": {"name":"Тяга саней к корпусу","tier":"rare"},
  "fedb-one-arm-long-bar-row": {"name":"Тяга Т-грифа одной рукой","tier":"rare"},
  "fedb-bent-over-one-arm-long-bar-row": {"name":"Тяга Т-грифа одной рукой в наклоне","tier":"rare"},
  "fedb-downward-facing-balance": {"name":"Баланс лицом вниз на фитболе","tier":"rare"},
  "fedb-kneeling-squat": {"name":"Присед с колен со штангой","tier":"rare"},
  "fedb-kneeling-jump-squat": {"name":"Прыжок из приседа с колен","tier":"rare"},
  "fedb-decline-smith-press": {"name":"Жим в Смите на отрицательном наклоне","tier":"retired","action":"duplicate","target":"fedb-smith-machine-decline-press"},
  "fedb-wide-grip-decline-barbell-bench-press": {"name":"Жим вниз широким хватом","tier":"retired","action":"variant","target":"fedb-decline-barbell-bench-press"},
  "fedb-incline-dumbbell-bench-with-palms-facing-in": {"name":"Жим гантелей на наклонной ладонями внутрь","tier":"retired","action":"variant","target":"fedb-incline-dumbbell-press"},
  "fedb-hammer-grip-incline-db-bench-press": {"name":"Жим гантелей на наклонной нейтральным хватом","tier":"retired","action":"variant","target":"fedb-incline-dumbbell-press"},
  "fedb-dumbbell-bench-press-with-neutral-grip": {"name":"Жим гантелей нейтральным хватом","tier":"retired","action":"variant","target":"dumbbell-bench-press"},
  "fedb-one-arm-dumbbell-bench-press": {"name":"Жим гантели лёжа одной рукой","tier":"retired","action":"variant","target":"dumbbell-bench-press"},
  "fedb-bench-press-powerlifting": {"name":"Жим лёжа (пауэрлифтинг)","tier":"retired","action":"variant","target":"bench-press"},
  "fedb-barbell-bench-press-medium-grip": {"name":"Жим лёжа средним хватом","tier":"retired","action":"variant","target":"bench-press"},
  "fedb-wide-grip-barbell-bench-press": {"name":"Жим лёжа широким хватом","tier":"retired","action":"variant","target":"bench-press"},
  "fedb-barbell-incline-bench-press-medium-grip": {"name":"Жим на наклонной средним хватом","tier":"retired","action":"variant","target":"incline-bench-press"},
  "fedb-dips-chest-version": {"name":"Отжимания на брусьях с акцентом на грудь","tier":"retired","action":"variant","target":"dips"},
  "fedb-incline-push-up-reverse-grip": {"name":"Отжимания на возвышении обратным хватом","tier":"retired","action":"variant","target":"fedb-incline-push-up"},
  "fedb-incline-push-up-medium": {"name":"Отжимания на среднем возвышении","tier":"retired","action":"variant","target":"fedb-incline-push-up"},
  "fedb-pushups-close-and-wide-hand-positions": {"name":"Отжимания со сменой узкой и широкой постановки","tier":"retired","action":"variant","target":"push-ups"},
  "fedb-push-up-wide": {"name":"Отжимания широким хватом","tier":"retired","action":"variant","target":"push-ups"},
  "fedb-dumbbell-flyes": {"name":"Разводка гантелей лёжа","tier":"retired","action":"duplicate","target":"dumbbell-fly"},
  "fedb-incline-dumbbell-flyes-with-a-twist": {"name":"Разводка гантелей на наклонной с поворотом","tier":"retired","action":"variant","target":"fedb-incline-dumbbell-flyes"},
  "fedb-one-arm-flat-bench-dumbbell-flye": {"name":"Разводка гантели лёжа одной рукой","tier":"retired","action":"variant","target":"dumbbell-fly"},
  "fedb-single-arm-cable-crossover": {"name":"Сведение одной рукой в кроссовере","tier":"retired","action":"variant","target":"fedb-cable-crossover"},
  "fedb-incline-push-up-wide": {"name":"Широкие отжимания на возвышении","tier":"retired","action":"variant","target":"fedb-incline-push-up"},
  "interval-bike": {"name":"Интервалы на велотренажёре","tier":"retired","action":"format","target":"stationary-bike"},
  "interval-rowing": {"name":"Интервалы на гребном тренажёре","tier":"retired","action":"format","target":"rowing-machine"},
  "interval-walking": {"name":"Интервальная ходьба","tier":"retired","action":"format","target":"walking"},
  "circuit-training": {"name":"Круговая тренировка","tier":"retired","action":"format"},
  "tabata": {"name":"Табата","tier":"retired","action":"format"},
  "amrap": {"name":"AMRAP","tier":"retired","action":"format"},
  "emom": {"name":"EMOM","tier":"retired","action":"format"},
  "fedb-3-4-sit-up": {"name":"Подъём корпуса на 3/4","tier":"retired","action":"variant","target":"fedb-sit-up"},
  "fedb-rope-crunch": {"name":"Скручивания с канатом в блоке","tier":"retired","action":"variant","target":"fedb-cable-crunch"},
  "fedb-weighted-crunches": {"name":"Скручивания с медболом","tier":"retired","action":"variant","target":"crunches"},
  "fedb-crunch-legs-on-exercise-ball": {"name":"Скручивания с ногами на фитболе","tier":"retired","action":"variant","target":"crunches"},
  "fedb-crunch-hands-overhead": {"name":"Скручивания с руками над головой","tier":"retired","action":"variant","target":"crunches"},
  "fedb-narrow-stance-hack-squats": {"name":"Гакк-присед с узкой постановкой","tier":"retired","action":"variant","target":"fedb-hack-squat"},
  "fedb-barbell-full-squat": {"name":"Глубокий присед со штангой","tier":"retired","action":"variant","target":"barbell-squat"},
  "fedb-narrow-stance-leg-press": {"name":"Жим ногами с узкой постановкой","tier":"retired","action":"variant","target":"leg-press"},
  "fedb-narrow-stance-squats": {"name":"Присед со штангой с узкой постановкой","tier":"retired","action":"variant","target":"barbell-squat"},
  "fedb-single-leg-leg-extension": {"name":"Разгибание одной ноги в тренажёре","tier":"retired","action":"variant","target":"leg-extension"},
  "fedb-romanian-deadlift": {"name":"Румынская тяга со штангой","tier":"retired","action":"duplicate","target":"romanian-deadlift"},
  "fedb-lying-leg-curls": {"name":"Сгибание ног лёжа в тренажёре","tier":"retired","action":"duplicate","target":"leg-curl"},
  "fedb-smith-machine-stiff-legged-deadlift": {"name":"Становая на прямых ногах в Смите","tier":"retired","action":"duplicate","target":"vital-smith-stiff-leg-deadlift"},
  "fedb-front-squat-clean-grip": {"name":"Фронтальный присед тяжелоатлетическим хватом","tier":"retired","action":"variant","target":"front-squat"},
  "fedb-standing-dumbbell-press": {"name":"Жим гантелей стоя","tier":"retired","action":"duplicate","target":"vital-standing-dumbbell-press"},
  "fedb-standing-palms-in-dumbbell-press": {"name":"Жим гантелей стоя нейтральным хватом","tier":"retired","action":"variant","target":"vital-standing-dumbbell-press"},
  "fedb-dumbbell-one-arm-shoulder-press": {"name":"Жим гантели над головой одной рукой","tier":"retired","action":"variant","target":"vital-standing-dumbbell-press"},
  "fedb-standing-palm-in-one-arm-dumbbell-press": {"name":"Жим гантели одной рукой нейтральным хватом","tier":"retired","action":"variant","target":"vital-standing-dumbbell-press"},
  "fedb-leverage-shoulder-press": {"name":"Жим над головой в рычажном тренажёре","tier":"retired","action":"duplicate","target":"fedb-machine-shoulder-military-press"},
  "fedb-external-rotation-with-band": {"name":"Наружная ротация плеча с резиной","tier":"retired","action":"duplicate","target":"band-external-rotation"},
  "fedb-reverse-machine-flyes": {"name":"Обратная разводка в тренажёре","tier":"retired","action":"duplicate","target":"vital-reverse-pec-deck"},
  "fedb-front-plate-raise": {"name":"Подъём блина перед собой","tier":"retired","action":"duplicate","target":"vital-plate-front-raise"},
  "fedb-front-dumbbell-raise": {"name":"Подъём гантелей перед собой","tier":"retired","action":"duplicate","target":"fedb-dumbbell-raise"},
  "fedb-standing-alternating-dumbbell-press": {"name":"Попеременный жим гантелей стоя","tier":"retired","action":"variant","target":"vital-standing-dumbbell-press"},
  "fedb-alternating-kettlebell-press": {"name":"Попеременный жим гирь","tier":"retired","action":"variant","target":"fedb-two-arm-kettlebell-military-press"},
  "fedb-alternating-cable-shoulder-press": {"name":"Попеременный жим над головой","tier":"retired","action":"variant","target":"fedb-cable-shoulder-press"},
  "fedb-bent-over-dumbbell-rear-delt-raise-with-head-on-bench": {"name":"Разводка гантелей на заднюю дельту с опорой головой","tier":"retired","action":"variant","target":"rear-delt-fly"},
  "fedb-dumbbell-one-arm-upright-row": {"name":"Тяга гантели к подбородку одной рукой","tier":"retired","action":"variant","target":"fedb-standing-dumbbell-upright-row"},
  "fedb-smith-machine-one-arm-upright-row": {"name":"Тяга к подбородку одной рукой в Смите","tier":"retired","action":"variant","target":"fedb-smith-machine-upright-row"},
  "fedb-barbell-shrug": {"name":"Шраги со штангой","tier":"retired","action":"duplicate","target":"shrugs"},
  "fedb-cross-body-hammer-curl": {"name":"Молоток к противоположному плечу","tier":"retired","action":"variant","target":"hammer-curl"},
  "fedb-dips-triceps-version": {"name":"Отжимания на брусьях (трицепс)","tier":"retired","action":"variant","target":"dips"},
  "fedb-incline-push-up-close-grip": {"name":"Отжимания на возвышении узким хватом","tier":"retired","action":"variant","target":"fedb-incline-push-up"},
  "fedb-parallel-bar-dip": {"name":"Отжимания на параллельных брусьях","tier":"retired","action":"duplicate","target":"dips"},
  "fedb-close-grip-push-up-off-of-a-dumbbell": {"name":"Отжимания узким хватом на гантелях","tier":"retired","action":"variant","target":"close-grip-push-up"},
  "fedb-flexor-incline-dumbbell-curls": {"name":"Подъём гантелей на бицепс на наклонной с супинацией","tier":"retired","action":"variant","target":"fedb-incline-dumbbell-curl"},
  "fedb-incline-inner-biceps-curl": {"name":"Подъём гантелей на внутренний пучок бицепса","tier":"retired","action":"variant","target":"fedb-incline-dumbbell-curl"},
  "fedb-seated-dumbbell-inner-biceps-curl": {"name":"Подъём гантелей на внутренний пучок бицепса сидя","tier":"retired","action":"variant","target":"fedb-seated-dumbbell-curl"},
  "fedb-close-grip-ez-bar-curl": {"name":"Подъём на бицепс узким хватом","tier":"retired","action":"variant","target":"fedb-ez-bar-curl"},
  "fedb-close-grip-standing-barbell-curl": {"name":"Подъём штанги на бицепс узким хватом стоя","tier":"retired","action":"variant","target":"barbell-curl"},
  "fedb-alternate-hammer-curl": {"name":"Попеременный молоток","tier":"retired","action":"variant","target":"hammer-curl"},
  "fedb-dumbbell-alternate-bicep-curl": {"name":"Попеременный подъём гантелей на бицепс","tier":"retired","action":"variant","target":"biceps-curl"},
  "fedb-alternate-incline-dumbbell-curl": {"name":"Попеременный подъём на бицепс на наклонной","tier":"retired","action":"variant","target":"fedb-incline-dumbbell-curl"},
  "fedb-reverse-grip-triceps-pushdown": {"name":"Разгибание на трицепс обратным хватом","tier":"retired","action":"variant","target":"triceps-pushdown"},
  "fedb-cable-one-arm-tricep-extension": {"name":"Разгибание руки на трицепс в блоке","tier":"retired","action":"variant","target":"triceps-pushdown"},
  "fedb-ez-bar-skullcrusher": {"name":"Французский жим с EZ-грифом","tier":"retired","action":"duplicate","target":"french-press"},
  "fedb-hyperextensions-back-extensions": {"name":"Гиперэкстензия для спины","tier":"retired","action":"duplicate","target":"hyperextension"},
  "fedb-inverted-row-with-straps": {"name":"Горизонтальные подтягивания на петлях","tier":"retired","action":"duplicate","target":"fedb-suspended-row"},
  "fedb-weighted-pull-ups": {"name":"Подтягивания с дополнительным весом","tier":"retired","action":"variant","target":"pull-ups"},
  "fedb-v-bar-pullup": {"name":"Подтягивания с треугольной рукоятью","tier":"retired","action":"variant","target":"pull-ups"},
  "fedb-mixed-grip-chin": {"name":"Подтягивания смешанным хватом","tier":"retired","action":"variant","target":"pull-ups"},
  "fedb-alternating-kettlebell-row": {"name":"Попеременная тяга гирь в наклоне","tier":"retired","action":"variant","target":"fedb-two-arm-kettlebell-row"},
  "fedb-rope-straight-arm-pulldown": {"name":"Пуловер прямыми руками с канатом в блоке","tier":"retired","action":"variant","target":"fedb-straight-arm-pulldown"},
  "fedb-full-range-of-motion-lat-pulldown": {"name":"Тяга верхнего блока в полной амплитуде","tier":"retired","action":"variant","target":"lat-pulldown"},
  "fedb-underhand-cable-pulldowns": {"name":"Тяга верхнего блока обратным хватом","tier":"retired","action":"variant","target":"lat-pulldown"},
  "fedb-v-bar-pulldown": {"name":"Тяга верхнего блока с треугольной рукоятью","tier":"retired","action":"variant","target":"lat-pulldown"},
  "fedb-close-grip-front-lat-pulldown": {"name":"Тяга верхнего блока узким хватом","tier":"retired","action":"variant","target":"lat-pulldown"},
  "fedb-wide-grip-lat-pulldown": {"name":"Тяга верхнего блока широким хватом","tier":"retired","action":"variant","target":"lat-pulldown"},
  "fedb-bent-over-two-dumbbell-row-with-palms-in": {"name":"Тяга гантелей в наклоне нейтральным хватом","tier":"retired","action":"variant","target":"fedb-bent-over-two-dumbbell-row"},
  "fedb-one-arm-dumbbell-row": {"name":"Тяга гантели одной рукой","tier":"retired","action":"duplicate","target":"dumbbell-row"},
  "fedb-bent-over-barbell-row": {"name":"Тяга штанги в наклоне","tier":"retired","action":"duplicate","target":"barbell-row"},
  "fedb-reverse-grip-bent-over-rows": {"name":"Тяга штанги в наклоне обратным хватом","tier":"retired","action":"variant","target":"barbell-row"},
}
