-- Apply the completed catalog-wide metric review to workouts that can still
-- be edited. Completed and cancelled history remains an immutable snapshot.
with metric_correction(exercise_ref, input_kind) as (
  values
    ('fedb-ab-roller', 'reps'),
    ('fedb-back-flyes-with-bands', 'reps'),
    ('fedb-backward-medicine-ball-throw', 'strength'),
    ('fedb-balance-board', 'duration'),
    ('fedb-ball-leg-curl', 'reps'),
    ('fedb-band-assisted-pull-up', 'reps'),
    ('fedb-band-good-morning', 'reps'),
    ('fedb-band-good-morning-pull-through', 'reps'),
    ('fedb-band-hip-adductions', 'reps'),
    ('fedb-band-pull-apart', 'reps'),
    ('fedb-band-skull-crusher', 'reps'),
    ('fedb-battling-ropes', 'duration'),
    ('fedb-bench-press-with-bands', 'reps'),
    ('fedb-bodyweight-mid-row', 'reps'),
    ('fedb-brachialis-smr', 'duration'),
    ('fedb-calf-raises-with-bands', 'reps'),
    ('fedb-chest-stretch-on-stability-ball', 'duration'),
    ('fedb-cross-over-with-bands', 'reps'),
    ('fedb-dips-chest-version', 'reps'),
    ('fedb-donkey-calf-raises', 'reps'),
    ('fedb-downward-facing-balance', 'duration'),
    ('fedb-exercise-ball-crunch', 'reps'),
    ('fedb-exercise-ball-pull-in', 'reps'),
    ('fedb-external-rotation-with-band', 'reps'),
    ('fedb-gironda-sternum-chins', 'reps'),
    ('fedb-hip-extension-with-bands', 'reps'),
    ('fedb-hip-flexion-with-band', 'reps'),
    ('fedb-hip-lift-with-band', 'reps'),
    ('fedb-hyperextensions-back-extensions', 'reps'),
    ('fedb-internal-rotation-with-band', 'reps'),
    ('fedb-inverted-row-with-straps', 'reps'),
    ('fedb-kipping-muscle-up', 'reps'),
    ('fedb-knee-hip-raise-on-parallel-bars', 'reps'),
    ('fedb-lateral-raise-with-bands', 'reps'),
    ('fedb-lying-glute', 'duration'),
    ('fedb-medicine-ball-full-twist', 'strength'),
    ('fedb-medicine-ball-scoop-throw', 'strength'),
    ('fedb-mixed-grip-chin', 'reps'),
    ('fedb-monster-walk', 'reps'),
    ('fedb-muscle-up', 'reps'),
    ('fedb-one-arm-chin-up', 'reps'),
    ('fedb-parallel-bar-dip', 'reps'),
    ('fedb-physioball-hip-bridge', 'reps'),
    ('fedb-piriformis-smr', 'duration'),
    ('fedb-platform-hamstring-slides', 'reps'),
    ('fedb-push-ups-with-feet-on-an-exercise-ball', 'reps'),
    ('fedb-ring-dips', 'reps'),
    ('fedb-rope-climb', 'reps'),
    ('fedb-seated-glute', 'duration'),
    ('fedb-shoulder-press-with-bands', 'reps'),
    ('fedb-sledgehammer-swings', 'strength'),
    ('fedb-suspended-push-up', 'reps'),
    ('fedb-suspended-row', 'reps'),
    ('fedb-upright-row-with-bands', 'reps'),
    ('fedb-vertical-swing', 'strength'),
    ('vital-band-lunge-ex562', 'reps'),
    ('vital-band-pushup-ex008', 'reps'),
    ('vital-banded-front-squat-ex567', 'reps'),
    ('vital-banded-glute-kick-ex568', 'reps'),
    ('vital-banded-one-arm-row-ex571', 'reps'),
    ('vital-banded-seated-abduction-ex239', 'reps'),
    ('vital-banded-seated-row-ex184', 'reps'),
    ('vital-gym-pro-r043-0101', 'reps'),
    ('vital-gym-pro-r072-0177', 'strength'),
    ('vital-gym-pro-r114-0266', 'duration'),
    ('vital-gym-pro-r121-0276', 'reps'),
    ('vital-gym-pro-r124-0286', 'reps'),
    ('vital-gym-pro-r134-1247', 'reps'),
    ('vital-gym-pro-r135-1248', 'reps'),
    ('vital-gym-pro-r137-1250', 'reps'),
    ('vital-gym-pro-r138-1251', 'reps'),
    ('vital-gym-pro-r139-1254', 'reps'),
    ('vital-gym-pro-r140-1255', 'reps'),
    ('vital-gym-pro-r141-1257', 'reps'),
    ('vital-gym-pro-r142-1258', 'reps'),
    ('vital-gym-pro-r157-1286', 'reps'),
    ('vital-gym-pro-r161-1292', 'reps'),
    ('vital-gym-pro-r166-1300', 'reps'),
    ('vital-gym-pro-r175-1311', 'reps'),
    ('vital-gym-pro-r176-1312', 'duration'),
    ('vital-gym-pro-r179-1315', 'reps'),
    ('vital-gym-pro-r190-1332', 'duration'),
    ('vital-gym-pro-r193-1336', 'reps'),
    ('vital-gym-pro-r200-1519', 'reps'),
    ('vital-gym-pro-r201-1520', 'reps'),
    ('vital-gym-pro-r209-1529', 'duration'),
    ('vital-gym-pro-r210-1530', 'reps'),
    ('vital-gym-pro-r212-1532', 'reps'),
    ('vital-gym-pro-r217-1537', 'duration'),
    ('vital-gym-pro-r219-1539', 'duration'),
    ('vital-gym-pro-r242-1567', 'reps'),
    ('vital-gym-pro-r243-1568', 'reps'),
    ('vital-gym-pro-r268-1597', 'duration'),
    ('vital-gym-pro-r275-1605', 'reps'),
    ('vital-gym-pro-r279-1613', 'reps'),
    ('vital-gym-pro-r280-1614', 'strength'),
    ('vital-gym-pro-r282-1617', 'reps'),
    ('vital-gym-pro-r283-1618', 'reps'),
    ('vital-gym-pro-r298-1640', 'reps'),
    ('vital-gym-pro-r299-1641', 'reps'),
    ('vital-gym-pro-r300-1642', 'reps'),
    ('vital-gym-pro-r303-1645', 'duration'),
    ('vital-gym-pro-r310-1350', 'duration'),
    ('vital-gym-pro-r393-1497', 'reps'),
    ('vital-gym-pro-r397-1516', 'reps'),
    ('vital-hip-abduction-ex603', 'strength'),
    ('vital-hip-adduction-ex604', 'strength'),
    ('vital-resistance-band-biceps-curl-ex158', 'reps'),
    ('vital-resistance-band-chest-press-ex232', 'reps'),
    ('vital-resistance-band-deadlift-ex197', 'reps'),
    ('vital-resistance-band-high-side-pull-ex279', 'reps'),
    ('vital-resistance-band-kneeling-crunch-ex498', 'reps'),
    ('vital-resistance-band-lat-pulldown-ex198', 'reps'),
    ('vital-resistance-band-overhead-triceps-extension-ex159', 'reps'),
    ('vital-resistance-band-squat-ex264', 'reps'),
    ('vital-resistance-band-w-raise-ex199', 'reps'),
    ('vital-stability-ball-deadbug-ex517', 'reps')
),
corrected as (
  update public.workout_exercises exercise
  set
    input_kind = metric.input_kind,
    updated_at = now()
  from public.workouts workout, metric_correction metric
  where workout.id = exercise.workout_id
    and workout.status in ('planned', 'in_progress')
    and exercise.exercise_source = 'system'
    and exercise.exercise_ref = metric.exercise_ref
    and exercise.input_kind is distinct from metric.input_kind
  returning exercise.workout_id
)
update public.workouts workout
set
  version = workout.version + 1,
  updated_at = now()
where workout.status in ('planned', 'in_progress')
  and workout.id in (select corrected.workout_id from corrected);
